"""
Freshness gate for the generated confidence / evidence matrix.

``docs/development/confidence-matrix.md`` and its machine-readable sibling
``tests/contracts/data/confidence_snapshot.json`` are generated by
``scripts/generate_confidence_matrix.py`` from four independent evidence layers
(the committed citation snapshot, the resolved rulepacks, the oracle values, and
a text scan of the test tree). Both outputs are a pure, timestamp-free function
of the tree, so the committed copies must be byte-identical to a fresh render.

Any edit that shifts one of those layers — a new pack value, a new oracle case,
a new decorated function, or a test that names a regulatory article for the
first time — makes the page stale until it is regenerated. This test fails in
that state, mirroring ``tests/contracts/test_docs_freshness.py``.

References:
- scripts/generate_confidence_matrix.py (the generator and its scoring rule)
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


def test_confidence_matrix_is_fresh() -> None:
    # Arrange / Act
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "generate_confidence_matrix.py"), "--check"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )

    # Assert
    assert result.returncode == 0, (
        "The confidence matrix page or snapshot no longer matches the evidence "
        "layers. Regenerate it (never hand-edit):\n"
        "  uv run python scripts/generate_confidence_matrix.py\n"
        f"{result.stderr}"
    )
