"""
Contract test for the release script's regeneration set.

Pipeline position:
    scripts/deploy.py::build_release -> generated docs -> release commit

Key responsibilities:
- Every generator that stamps the package version into its output is regenerated
  by the release script

Why this exists
---------------
Two generated pages and one snapshot embed the package version. Bumping the
version is therefore, by itself, enough to make them stale and turn their
freshness contract tests red — and the release script runs the test suite
*before* the bump, so the suite measures a tree in which the staleness does not
yet exist. v0.3.25 shipped a red CI run for exactly this reason.

The fix was to regenerate those targets inside `build_release`. This test is what
stops the fix from decaying: a *new* version-stamped generator added later, and
not wired into the release, would reintroduce the identical failure. Discovery is
by inspection rather than by a hand-maintained list, because a hand-maintained
list is the thing that was wrong in the first place.

References:
- docs/development/escape-log.md — 2026-08-11 entry on the stale generated artifacts
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DEPLOY_SCRIPT = REPO_ROOT / "scripts" / "deploy.py"
GENERATOR_GLOB = "generate_*.py"


def _version_stamped_generators() -> list[Path]:
    """Return generators that read the package version out of pyproject.toml."""
    found = []
    for script in sorted((REPO_ROOT / "scripts").glob(GENERATOR_GLOB)):
        content = script.read_text(encoding="utf-8")
        if "pyproject.toml" in content and '"version"' in content:
            found.append(script)
    return found


def test_discovery_finds_the_version_stamped_generators() -> None:
    """Silence must not read as success — an empty sweep is a broken sweep."""
    # Arrange / Act
    generators = _version_stamped_generators()

    # Assert
    assert generators, (
        "No version-stamped generators discovered. Either the detection heuristic "
        "in this test has drifted from how the generators read pyproject.toml, or "
        "the generators moved. Fix the heuristic — do not delete the test, which "
        "would make the check below vacuously true."
    )


def test_release_script_regenerates_every_version_stamped_generator() -> None:
    """A generator that stamps the version must be rerun when the version changes."""
    # Arrange
    deploy_source = DEPLOY_SCRIPT.read_text(encoding="utf-8")

    # Act
    missing = [
        script.name for script in _version_stamped_generators() if script.name not in deploy_source
    ]

    # Assert
    assert not missing, (
        "These generators stamp the package version into their output but are not "
        f"regenerated by scripts/deploy.py: {', '.join(missing)}.\n"
        "A version bump alone will make their targets stale, and the release "
        "script's own test run happens before the bump, so nothing local will "
        "catch it — CI on the release commit will. Add them to build_release() and "
        "their targets to GIT_STAGE_FILES."
    )
