"""
Agent-instruction freshness gates (repo-root ``AGENTS.md``).

Two agent CLIs work this repo and neither reads the other's instruction file:
Claude Code injects ``CLAUDE.md`` and never looks at ``AGENTS.md``; OpenAI
Codex CLI injects the repo-root ``AGENTS.md`` and never looks at ``CLAUDE.md``
(confirmed against Codex 0.151.0 via ``codex debug prompt-input``). While
``AGENTS.md`` was a hand-written 49-line subset it drifted, and drift in an
instruction file is not cosmetic — it instructs a coding agent to write code.

The escaped defect these gates close: ``AGENTS.md`` told Codex to implement
domain logic as ``@pl.api.register_lazyframe_namespace`` in ``namespace.py``
files. That pattern is extinct and banned outright by ``scripts/arch_check.py``
check 14 (no allowlist), so every Codex session was being steered at a pattern
the pre-commit gate rejects. Nothing failed, because nothing read the file.

``AGENTS.md`` is now generated by ``scripts/sync_agent_instructions.py`` from
``CLAUDE.md`` (with ``CLAUDE-ONLY`` fenced blocks stripped) plus
``.agents/codex-appendix.md``, and the checks below are what make the
generation binding rather than advisory.

References:
- CLAUDE.md "Documentation" — generated pages are never hand-edited
- CLAUDE.md "The learning loop" — prose that fails twice earns an executable check
- scripts/arch_check.py check 14 — the Polars-namespace ban this guards
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
AGENTS_MD = REPO_ROOT / "AGENTS.md"
GENERATOR = REPO_ROOT / "scripts" / "sync_agent_instructions.py"
CLAUDE_AGENTS_DIR = REPO_ROOT / ".claude" / "agents"
CLAUDE_COMMANDS_DIR = REPO_ROOT / ".claude" / "commands"

#: Roster names CLAUDE.md deliberately leaves outside the fence. Empty is the
#: goal. An entry here is a Claude-only affordance that Codex is allowed to read
#: about while being unable to act on it, so it needs a written justification
#: beside it — the same contract as the allowlists at the top of
#: ``scripts/arch_check.py``.
SHARED_BY_DESIGN: frozenset[str] = frozenset()

sys.path.insert(0, str(REPO_ROOT / "scripts"))

# Imported rather than driven through the CLI: the fence-strictness gates are
# about behaviour the CLI only ever reports the outcome of.
from sync_agent_instructions import (  # noqa: E402
    END_MARKER,
    START_MARKER,
    FenceError,
    strip_claude_only,
)


def _run_generator(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(GENERATOR), *args],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )


def test_agents_md_matches_a_fresh_render() -> None:
    """The committed AGENTS.md must match a fresh render, line ending aside.

    The comparison runs through ``Path.read_text``, so it is deliberately
    line-ending insensitive: this repo has no ``.gitattributes`` and CLAUDE.md is
    CRLF in a Windows checkout, so a byte comparison would fail the gate on
    platform rather than on drift.
    """
    # Arrange / Act
    result = _run_generator("--check")

    # Assert
    assert result.returncode == 0, (
        "AGENTS.md no longer matches CLAUDE.md + .agents/codex-appendix.md. It is a "
        "generated file — edit the source, never AGENTS.md itself, then regenerate:\n"
        "  uv run python scripts/sync_agent_instructions.py\n"
        f"{result.stderr}"
    )


def test_agents_md_does_not_teach_the_banned_polars_namespace_pattern() -> None:
    """AGENTS.md must not steer Codex at a pattern arch_check check 14 bans.

    This is the regression guard for the defect that motivated generating the
    file at all: the hand-written AGENTS.md carried
    ``**Namespaces**: domain logic via @pl.api.register_lazyframe_namespace in
    namespace.py files`` for the whole life of the fold migration, against a
    ``scripts/arch_check.py`` check 14 that rejects every registration form
    under ``src/`` with no allowlist. Guarding the *pattern* rather than that
    one sentence keeps the check meaningful if the prose is ever reworded.
    """
    # Arrange
    text = AGENTS_MD.read_text(encoding="utf-8")

    # Act
    registrations = [
        form
        for form in (
            "register_lazyframe_namespace",
            "register_dataframe_namespace",
            "register_expr_namespace",
            "register_series_namespace",
        )
        if form in text
    ]

    # Assert
    assert not registrations, (
        f"AGENTS.md names {registrations}. Polars namespace registrations are extinct "
        "(migration Phase 4) and banned under src/ by scripts/arch_check.py check 14, so "
        "an instruction file that teaches the pattern sends Codex straight into the "
        "pre-commit gate. Calculator logic is plain typed functions composed via "
        ".pipe(fn, config)."
    )


def _claude_only_roster() -> set[str]:
    """Every Claude-Code-only affordance, enumerated from disk rather than recalled.

    The population is defined by the filesystem and grows whenever anyone adds a
    file under ``.claude/agents/`` or ``.claude/commands/``. A hand-written tuple
    of names cannot know that, and its silence when a new one leaks is
    indistinguishable from success.
    """
    agents = {path.stem for path in CLAUDE_AGENTS_DIR.glob("*.md")}
    commands = {f"/{path.stem}" for path in CLAUDE_COMMANDS_DIR.glob("*.md")}
    return agents | commands


def test_claude_only_roster_is_absent_from_agents_md() -> None:
    """No role-agent or slash command may reach a reader that cannot run one.

    Codex has no ``.claude/agents/`` registry and no slash commands, so naming
    one at it is at best noise and at worst an instruction it will try to follow.
    """
    # Arrange
    roster = _claude_only_roster()
    assert roster, (
        f"no files under {CLAUDE_AGENTS_DIR.name}/ or {CLAUDE_COMMANDS_DIR.name}/ — the "
        "roster is empty and this gate would pass vacuously."
    )
    text = AGENTS_MD.read_text(encoding="utf-8")

    # Act
    # The negative lookahead stops `/next-doc` matching inside `/next-docs` and
    # reporting a leak that is really its sibling's; the sibling is still caught
    # on its own name.
    leaked = sorted(
        name
        for name in roster - SHARED_BY_DESIGN
        if re.search(rf"{re.escape(name)}(?![\w-])", text)
    )

    # Assert
    assert not leaked, (
        f"AGENTS.md names Claude-only affordances: {leaked}. They live in `.claude/` and "
        "are dispatchable only from Claude Code, so the prose that names them belongs "
        "inside a CLAUDE-ONLY fence in CLAUDE.md. Fence the mechanics and keep the "
        "reasoning shared — do not add the name to SHARED_BY_DESIGN to make this pass."
    )


def test_shared_sections_are_present_in_agents_md() -> None:
    """The shared body must actually reach Codex — an over-eager strip is a defect too."""
    # Arrange
    text = AGENTS_MD.read_text(encoding="utf-8")

    # Act
    missing = [
        marker
        for marker in (
            "engine/orchestrator.py::run_stages",  # Architecture: the fold
            "rulepack",  # the value home
            "uv run python tests/fixtures/generate_all.py",  # Validation Gate
            "The learning loop",  # explicitly kept shared
        )
        if marker not in text
    ]

    # Assert
    assert not missing, (
        f"AGENTS.md is missing shared content: {missing}. AGENTS.md is CLAUDE.md minus the "
        "CLAUDE-ONLY blocks, so anything absent here was either fenced by mistake or "
        "deleted from CLAUDE.md."
    )


def test_generated_banner_names_its_sources_and_regeneration_command() -> None:
    """A generated file that does not say so invites the hand-edit it cannot keep."""
    # Arrange
    head = AGENTS_MD.read_text(encoding="utf-8")[:2000]

    # Assert
    assert "do not hand-edit" in head.lower()
    assert "CLAUDE.md" in head
    assert ".agents/codex-appendix.md" in head
    assert "uv run python scripts/sync_agent_instructions.py" in head


def test_unbalanced_fences_are_an_error_not_a_silent_pass_through() -> None:
    """A fence that fails open publishes exactly what it exists to withhold."""
    # Arrange
    unclosed = f"shared\n\n{START_MARKER}\nsecret\n"
    unopened = f"shared\n\n{END_MARKER}\n"
    nested = f"{START_MARKER}\nsecret\n{START_MARKER}\nmore\n{END_MARKER}\n{END_MARKER}\n"

    # Act / Assert
    for source in (unclosed, unopened, nested):
        with pytest.raises(FenceError):
            strip_claude_only(source)


@pytest.mark.parametrize(
    "near_miss",
    [
        "<!-- claude-only:start -->",
        "<!-- Claude-Only:START -->",
        "<!-- CLAUDE_ONLY:START -->",
        "<!-- CLAUDE ONLY:START -->",
        "<!-- CLUADE-ONLY:START -->",
        "<!-- CLUADE-ONLY:STRT -->",
        "<!-- CLAUDE-ONLY:STRT -->",
        "<!-- CLAUDE-ONLY:START --> trailing prose",
        "<!-- claude-only:end -->",
    ],
)
def test_a_mistyped_sentinel_is_an_error_not_a_leak(near_miss: str) -> None:
    """The sentinel is guarded, not just the kind.

    An unrecognised marker does not merely fail to open a block: it renders as
    ordinary text, and everything the block was meant to withhold is published
    underneath it. So every near-miss spelling has to be a hard error.

    The first version of this gate exercised only ``STRT`` — a misspelt *kind* —
    while the implementation guarded only the kind too. Test and code were
    written from the same sentence, so the test could only ever confirm the
    assumption it shared (`.claude/LESSONS.md` B3). Five sentinel misspellings
    leaked underneath it.
    """
    # Arrange / Act / Assert
    with pytest.raises(FenceError):
        strip_claude_only(f"shared\n\n{near_miss}\nsecret\n")


# --- The two directions of the near-miss predicate ------------------------
#
# Kept visibly apart because they encode opposite intents, and a reader who
# conflates them will "fix" the wrong one. Below: comments that must survive.
# After: comments that are innocent-looking but must STILL hard-error, because
# the predicate is deliberately biased that way.


@pytest.mark.parametrize(
    "benign",
    [
        "<!-- BEGIN GENERATED: crr_sa_risk_weights -->",
        "<!-- END GENERATED: crr_sa_risk_weights -->",
        "<!-- GENERATED FILE. DO NOT EDIT BY HAND. -->",
        "<!-- prettier-ignore -->",
    ],
)
def test_an_unrelated_html_comment_passes_through(benign: str) -> None:
    """The near-miss detector must not seize on every comment in the file.

    CLAUDE.md already carries ``<!-- BEGIN/END GENERATED: id -->`` in prose, so
    the predicate has to leave ordinary tooling comments alone.
    """
    # Arrange
    source = f"shared\n\n{benign}\n\nmore\n"

    # Act
    stripped = strip_claude_only(source)

    # Assert
    assert benign in stripped


@pytest.mark.parametrize(
    "innocent_but_rejected",
    [
        "<!-- this section is Claude only, for now -->",
        "<!-- ONLY:START of the appendix -->",
    ],
)
def test_an_innocent_comment_resembling_a_marker_is_rejected_by_design(
    innocent_but_rejected: str,
) -> None:
    """Over-triggering is the accepted cost, and this pins it so nobody "fixes" it.

    Neither of these is a marker. Both hard-error anyway, and that is correct:
    a false positive is a loud error naming the line, resolved by rewording one
    comment. A false negative is silent and total — the unrecognised marker
    renders as text and the entire block it was meant to withhold is published
    into AGENTS.md, where nothing downstream ever notices.

    So this test exists to stop a well-meaning reader treating the rejection as
    a bug and widening the predicate, which would reopen the fail-open leak for
    the whole category. **The resolution is to reword the comment**, or to put
    it in a fenced code block where markers are inert. If this test ever has to
    change, the burden is showing the leak stays closed.
    """
    # Arrange / Act / Assert
    with pytest.raises(FenceError):
        strip_claude_only(f"shared\n\n{innocent_but_rejected}\n\nmore\n")


def test_markers_inside_a_fenced_code_block_are_inert() -> None:
    """Documenting the grammar in a code block must not strip the documentation."""
    # Arrange
    source = f"before\n\n```\n{START_MARKER}\nexample body\n{END_MARKER}\n```\n\nafter\n"

    # Act
    stripped = strip_claude_only(source)

    # Assert
    assert START_MARKER in stripped
    assert "example body" in stripped
    assert stripped.count("```") == 2


def test_stripping_a_block_leaves_no_double_blank_line_scar() -> None:
    """Removing a section must not leave a blank-line pair where it stood."""
    # Arrange
    source = f"before\n\n{START_MARKER}\n\n## Fenced\n\nbody\n\n{END_MARKER}\n\nafter\n"

    # Act
    stripped = strip_claude_only(source)

    # Assert
    assert stripped == "before\n\nafter"
    assert "\n\n\n" not in stripped


def test_prose_that_quotes_a_marker_is_not_treated_as_a_marker() -> None:
    """CLAUDE.md documents the fence grammar in prose; that must still render."""
    # Arrange
    source = f"- Wrap it in `{START_MARKER}` / `{END_MARKER}` markers.\n"

    # Act
    stripped = strip_claude_only(source)

    # Assert
    assert stripped == source.rstrip("\n")
