"""
Independent oracle derivations.

This script is the SOLE programmatic source of truth for the expected RWA
values in `expected_values.json`. It uses ONLY Python stdlib (`hashlib`,
`json`, `pathlib`) plus the sibling `derivations/` package -- which is itself
stdlib-only. It DOES NOT IMPORT `rwa_calc`.

Each oracle produced by `derivations/` corresponds to a section in
`ORACLE_DERIVATIONS.md` with the same identifier (ORC-001, ORC-002, ...). The
arithmetic there must produce the same numbers shown in that document.

Run:
    uv run python tests/oracle/derive.py

Output:
    tests/oracle/expected_values.json
        Embeds a SHA-256 hash of ORACLE_DERIVATIONS.md under
        `derivations_doc_hash`. Line endings are normalised to LF before
        hashing so the hash is stable across Windows / Unix.
"""

from __future__ import annotations

import hashlib
import json
import sys
from collections import Counter
from pathlib import Path

# Run as a script (`uv run python tests/oracle/derive.py`), sys.path[0] is this
# directory rather than the repo root, so the package import below would fail.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from tests.oracle.derivations import all_oracles  # noqa: E402

HERE = Path(__file__).parent
DOC_PATH = HERE / "ORACLE_DERIVATIONS.md"
JSON_PATH = HERE / "expected_values.json"


def doc_hash() -> str:
    """SHA-256 of the derivations doc, with line endings normalised to LF.

    The normalisation makes the hash stable across CRLF (Windows) and LF
    (Unix) checkouts.
    """
    raw = DOC_PATH.read_bytes().replace(b"\r\n", b"\n")
    return hashlib.sha256(raw).hexdigest()


def main() -> None:
    oracles = all_oracles()
    payload = {
        "_doc": (
            "Generated by tests/oracle/derive.py. Do NOT hand-edit. "
            "To change values, edit ORACLE_DERIVATIONS.md and the "
            "tests/oracle/derivations/ modules together, then re-run derive.py."
        ),
        "derivations_doc": "ORACLE_DERIVATIONS.md",
        "derivations_doc_hash_algorithm": "sha256-lf-normalised",
        "derivations_doc_hash": doc_hash(),
        "tolerance_relative": 1e-6,
        "tolerance_absolute_minor": 0.01,
        "oracles": oracles,
    }
    JSON_PATH.write_text(json.dumps(payload, indent=2) + "\n")

    by_phase = Counter(o["phase"] for o in oracles)
    by_framework = Counter(o["framework"] for o in oracles)
    print(f"Wrote {JSON_PATH.name} with {len(oracles)} oracle exposures.")
    print(f"  by phase:     {dict(sorted(by_phase.items()))}")
    print(f"  by framework: {dict(sorted(by_framework.items()))}")
    print(f"Derivations doc hash: {payload['derivations_doc_hash']}")


if __name__ == "__main__":
    main()
