"""
Basel 3.1 SA risk weight tables (PRA PS9/24 / BCBS CRE20).

Provides LTV-band based risk weight tables for real estate exposures,
ADC treatment, revised CQS-based risk weights, SCRA institution weights,
investment-grade corporate treatment, and subordinated debt treatment
under the Basel 3.1 framework.

Pipeline position:
    Used by SACalculator._apply_risk_weights() when config.is_basel_3_1

Key responsibilities:
- LTV-band risk weight lookup for residential RE (general + income-producing)
- LTV-band risk weight lookup for commercial RE (general + income-producing)
- ADC exposure risk weight (150% / 100% pre-sold)
- Revised CQS-based corporate risk weights (CQS3: 75%, CQS5: 100%)
- SCRA-based institution risk weights for unrated exposures (Grade A/B/C)
- Investment-grade corporate treatment (65%)
- SME corporate treatment (85%)
- Subordinated debt treatment (150% flat)
- Polars expression builders for vectorized lookups

References:
    - CRE20.7-15: Sovereign risk weights (unchanged from CRR)
    - CRE20.16-21: Institution risk weights (ECRA rated + SCRA unrated)
    - CRE20.22-26: Corporate risk weights (revised CQS, investment-grade, SME)
    - CRE20.47: Subordinated debt (150% flat)
    - CRE20.73: Residential RE (general) whole-loan approach
    - CRE20.82: Residential RE (income-producing) whole-loan approach
    - CRE20.85: Commercial RE (general) preferential treatment
    - CRE20.86: Commercial RE (income-producing) LTV bands
    - CRE20.87-88: ADC exposures
    - PRA PS9/24 Chapter 4: UK adoption of BCBS SA risk weights
"""

from __future__ import annotations

from decimal import Decimal

import polars as pl

# =============================================================================
# RESIDENTIAL REAL ESTATE — GENERAL (CRE20.73)
# Not materially dependent on cash flows generated by the property
# Whole-loan approach (PRA PS9/24)
# =============================================================================

B31_RESIDENTIAL_GENERAL_LTV_BANDS: list[dict[str, Decimal]] = [
    {"ltv_lower": Decimal("0.00"), "ltv_upper": Decimal("0.50"), "risk_weight": Decimal("0.20")},
    {"ltv_lower": Decimal("0.50"), "ltv_upper": Decimal("0.60"), "risk_weight": Decimal("0.25")},
    {"ltv_lower": Decimal("0.60"), "ltv_upper": Decimal("0.70"), "risk_weight": Decimal("0.25")},
    {"ltv_lower": Decimal("0.70"), "ltv_upper": Decimal("0.80"), "risk_weight": Decimal("0.30")},
    {"ltv_lower": Decimal("0.80"), "ltv_upper": Decimal("0.90"), "risk_weight": Decimal("0.40")},
    {"ltv_lower": Decimal("0.90"), "ltv_upper": Decimal("1.00"), "risk_weight": Decimal("0.50")},
    {"ltv_lower": Decimal("1.00"), "ltv_upper": Decimal("999.0"), "risk_weight": Decimal("0.70")},
]

# =============================================================================
# RESIDENTIAL REAL ESTATE — INCOME-PRODUCING (CRE20.82)
# Materially dependent on cash flows generated by the property
# =============================================================================

B31_RESIDENTIAL_INCOME_LTV_BANDS: list[dict[str, Decimal]] = [
    {"ltv_lower": Decimal("0.00"), "ltv_upper": Decimal("0.50"), "risk_weight": Decimal("0.30")},
    {"ltv_lower": Decimal("0.50"), "ltv_upper": Decimal("0.60"), "risk_weight": Decimal("0.35")},
    {"ltv_lower": Decimal("0.60"), "ltv_upper": Decimal("0.70"), "risk_weight": Decimal("0.45")},
    {"ltv_lower": Decimal("0.70"), "ltv_upper": Decimal("0.80"), "risk_weight": Decimal("0.50")},
    {"ltv_lower": Decimal("0.80"), "ltv_upper": Decimal("0.90"), "risk_weight": Decimal("0.60")},
    {"ltv_lower": Decimal("0.90"), "ltv_upper": Decimal("1.00"), "risk_weight": Decimal("0.75")},
    {"ltv_lower": Decimal("1.00"), "ltv_upper": Decimal("999.0"), "risk_weight": Decimal("1.05")},
]

# =============================================================================
# COMMERCIAL REAL ESTATE — INCOME-PRODUCING (CRE20.86)
# Materially dependent on cash flows generated by the property
# =============================================================================

B31_COMMERCIAL_INCOME_LTV_BANDS: list[dict[str, Decimal]] = [
    {"ltv_lower": Decimal("0.00"), "ltv_upper": Decimal("0.60"), "risk_weight": Decimal("0.70")},
    {"ltv_lower": Decimal("0.60"), "ltv_upper": Decimal("0.80"), "risk_weight": Decimal("0.90")},
    {"ltv_lower": Decimal("0.80"), "ltv_upper": Decimal("999.0"), "risk_weight": Decimal("1.10")},
]

# =============================================================================
# COMMERCIAL REAL ESTATE — GENERAL (CRE20.85)
# Not materially dependent on cash flows
# Preferential treatment: min(60%, counterparty RW) if LTV ≤ 60%
# =============================================================================

B31_COMMERCIAL_GENERAL_LTV_THRESHOLD = Decimal("0.60")
B31_COMMERCIAL_GENERAL_PREFERENTIAL_CAP = Decimal("0.60")

# =============================================================================
# ADC EXPOSURES (CRE20.87-88)
# =============================================================================

B31_ADC_RISK_WEIGHT = Decimal("1.50")
B31_ADC_PRESOLD_RISK_WEIGHT = Decimal("1.00")

# =============================================================================
# CORPORATE CQS-BASED RISK WEIGHTS — BASEL 3.1 (CRE20.22-26)
# Differs from CRR: CQS3 = 75% (was 100%), CQS5 = 100% (was 150%)
# =============================================================================

B31_CORPORATE_RISK_WEIGHTS: dict[int | None, Decimal] = {
    1: Decimal("0.20"),  # AAA to AA-
    2: Decimal("0.50"),  # A+ to A-
    3: Decimal("0.75"),  # BBB+ to BBB- (CRR: 100%)
    4: Decimal("1.00"),  # BB+ to BB-
    5: Decimal("1.00"),  # B+ to B- (CRR: 150%)
    6: Decimal("1.50"),  # CCC+ and below
    None: Decimal("1.00"),  # Unrated
}

# Investment-grade corporate: 65% (CRE20.47-49)
# Qualifying: publicly traded + investment grade external rating
B31_CORPORATE_INVESTMENT_GRADE_RW = Decimal("0.65")

# SME corporate: 85% (CRE20.47-49)
# Qualifying: turnover <= EUR 50m, unrated
B31_CORPORATE_SME_RW = Decimal("0.85")

# =============================================================================
# SCRA-BASED INSTITUTION RISK WEIGHTS — BASEL 3.1 (CRE20.16-21)
# Standardised Credit Risk Assessment Approach for unrated institutions.
# Replaces CRR due-diligence assessment for unrated.
# Rated institutions use ECRA (same as CRR Art. 120-121).
# =============================================================================

B31_SCRA_RISK_WEIGHTS: dict[str, Decimal] = {
    "A": Decimal("0.40"),  # CET1 > 14%, Leverage > 5%, meets all requirements
    "B": Decimal("0.75"),  # CET1 > 5.5%, Leverage > 3%, meets minimums
    "C": Decimal("1.50"),  # Below minimum requirements
}

# =============================================================================
# SUBORDINATED DEBT RISK WEIGHT — BASEL 3.1 (CRE20.47)
# Flat 150% for all subordinated debt (institution + corporate)
# =============================================================================

B31_SUBORDINATED_DEBT_RW = Decimal("1.50")


def _create_b31_corporate_df() -> pl.DataFrame:
    """Create Basel 3.1 corporate risk weight lookup DataFrame."""
    return pl.DataFrame(
        {
            "cqs": [1, 2, 3, 4, 5, 6, None],
            "risk_weight": [0.20, 0.50, 0.75, 1.00, 1.00, 1.50, 1.00],
            "exposure_class": ["CORPORATE"] * 7,
        }
    ).with_columns(
        [
            pl.col("cqs").cast(pl.Int8),
            pl.col("risk_weight").cast(pl.Float64),
        ]
    )


def get_b31_combined_cqs_risk_weights(use_uk_deviation: bool = True) -> pl.DataFrame:
    """
    Get combined CQS-based risk weight table for Basel 3.1 joins.

    Uses Basel 3.1 corporate weights (CQS3=75%, CQS5=100%) while
    sovereign and institution ECRA weights remain the same as CRR.

    Args:
        use_uk_deviation: Whether to use UK-specific institution weights

    Returns:
        Combined DataFrame with columns: exposure_class, cqs, risk_weight
    """
    from rwa_calc.data.tables.crr_risk_weights import (
        _create_cgcb_df,
        _create_institution_df,
    )

    return pl.concat(
        [
            _create_cgcb_df().select(["exposure_class", "cqs", "risk_weight"]),
            _create_institution_df(use_uk_deviation).select(
                ["exposure_class", "cqs", "risk_weight"]
            ),
            _create_b31_corporate_df().select(["exposure_class", "cqs", "risk_weight"]),
        ]
    )


# =============================================================================
# POLARS EXPRESSION BUILDERS
# =============================================================================


def b31_residential_rw_expr() -> pl.Expr:
    """
    Polars expression for Basel 3.1 residential RE risk weights (whole-loan).

    Branches on has_income_cover to select general vs income-producing table.

    Requires columns: ltv (Float64), has_income_cover (Boolean)

    Returns:
        Expression resolving to the LTV-band risk weight
    """
    ltv = pl.col("ltv").fill_null(1.0)
    is_income = pl.col("has_income_cover").fill_null(False)

    # General residential (CRE20.73)
    general = (
        pl.when(ltv <= 0.50)
        .then(pl.lit(0.20))
        .when(ltv <= 0.60)
        .then(pl.lit(0.25))
        .when(ltv <= 0.70)
        .then(pl.lit(0.25))
        .when(ltv <= 0.80)
        .then(pl.lit(0.30))
        .when(ltv <= 0.90)
        .then(pl.lit(0.40))
        .when(ltv <= 1.00)
        .then(pl.lit(0.50))
        .otherwise(pl.lit(0.70))
    )

    # Income-producing residential (CRE20.82)
    income = (
        pl.when(ltv <= 0.50)
        .then(pl.lit(0.30))
        .when(ltv <= 0.60)
        .then(pl.lit(0.35))
        .when(ltv <= 0.70)
        .then(pl.lit(0.45))
        .when(ltv <= 0.80)
        .then(pl.lit(0.50))
        .when(ltv <= 0.90)
        .then(pl.lit(0.60))
        .when(ltv <= 1.00)
        .then(pl.lit(0.75))
        .otherwise(pl.lit(1.05))
    )

    return pl.when(is_income).then(income).otherwise(general)


def b31_commercial_rw_expr(counterparty_rw_col: str = "_cqs_risk_weight") -> pl.Expr:
    """
    Polars expression for Basel 3.1 commercial RE risk weights (whole-loan).

    General CRE (CRE20.85): min(60%, counterparty RW) if LTV ≤ 60%, else counterparty RW.
    Income-producing CRE (CRE20.86): LTV-band risk weights 70%/90%/110%.

    Requires columns: ltv, has_income_cover, and the counterparty RW column

    Args:
        counterparty_rw_col: Column containing the CQS-based counterparty risk weight

    Returns:
        Expression resolving to the risk weight
    """
    ltv = pl.col("ltv").fill_null(1.0)
    is_income = pl.col("has_income_cover").fill_null(False)
    cp_rw = pl.col(counterparty_rw_col).fill_null(1.0)

    # Income-producing CRE (CRE20.86)
    income = (
        pl.when(ltv <= 0.60)
        .then(pl.lit(0.70))
        .when(ltv <= 0.80)
        .then(pl.lit(0.90))
        .otherwise(pl.lit(1.10))
    )

    # General CRE (CRE20.85): preferential if LTV ≤ 60%
    general = pl.when(ltv <= 0.60).then(pl.min_horizontal(pl.lit(0.60), cp_rw)).otherwise(cp_rw)

    return pl.when(is_income).then(income).otherwise(general)


def b31_adc_rw_expr() -> pl.Expr:
    """
    Polars expression for Basel 3.1 ADC risk weights (CRE20.87-88).

    - 150% for ADC exposures
    - 100% if pre-sold/pre-let to qualifying buyer

    Requires columns: is_presold (Boolean)

    Returns:
        Expression resolving to 1.50 or 1.00
    """
    return pl.when(pl.col("is_presold").fill_null(False)).then(pl.lit(1.00)).otherwise(pl.lit(1.50))


# =============================================================================
# SCALAR LOOKUP FUNCTIONS (for single-exposure convenience)
# =============================================================================


def lookup_b31_residential_rw(
    ltv: Decimal,
    is_income_producing: bool = False,
) -> tuple[Decimal, str]:
    """
    Look up Basel 3.1 residential RE risk weight for a single exposure.

    Args:
        ltv: Loan-to-value ratio
        is_income_producing: Whether materially dependent on property cash flows

    Returns:
        Tuple of (risk_weight, description)
    """
    bands = (
        B31_RESIDENTIAL_INCOME_LTV_BANDS
        if is_income_producing
        else B31_RESIDENTIAL_GENERAL_LTV_BANDS
    )
    label = "income-producing" if is_income_producing else "general"

    for band in bands:
        if ltv <= band["ltv_upper"]:
            rw = band["risk_weight"]
            return rw, f"B31 RRE ({label}): {float(rw):.0%} (LTV {float(ltv):.0%})"

    rw = bands[-1]["risk_weight"]
    return rw, f"B31 RRE ({label}): {float(rw):.0%} (LTV > 100%)"


def lookup_b31_commercial_rw(
    ltv: Decimal,
    counterparty_rw: Decimal = Decimal("1.00"),
    is_income_producing: bool = False,
) -> tuple[Decimal, str]:
    """
    Look up Basel 3.1 commercial RE risk weight for a single exposure.

    Args:
        ltv: Loan-to-value ratio
        counterparty_rw: CQS-based risk weight of the counterparty (for general CRE)
        is_income_producing: Whether materially dependent on property cash flows

    Returns:
        Tuple of (risk_weight, description)
    """
    if is_income_producing:
        for band in B31_COMMERCIAL_INCOME_LTV_BANDS:
            if ltv <= band["ltv_upper"]:
                rw = band["risk_weight"]
                return rw, f"B31 CRE (income-producing): {float(rw):.0%} (LTV {float(ltv):.0%})"
        rw = B31_COMMERCIAL_INCOME_LTV_BANDS[-1]["risk_weight"]
        return rw, f"B31 CRE (income-producing): {float(rw):.0%} (LTV > 80%)"

    # General CRE (CRE20.85)
    if ltv <= B31_COMMERCIAL_GENERAL_LTV_THRESHOLD:
        rw = min(B31_COMMERCIAL_GENERAL_PREFERENTIAL_CAP, counterparty_rw)
        return rw, f"B31 CRE (general): {float(rw):.0%} (LTV {float(ltv):.0%})"

    return (
        counterparty_rw,
        f"B31 CRE (general): {float(counterparty_rw):.0%} (LTV {float(ltv):.0%} > 60%)",
    )
