"""
Basel 3.1 SA risk weight tables (PRA PS9/24 / BCBS CRE20).

Provides LTV-band based risk weight tables for real estate exposures
and ADC treatment under the Basel 3.1 framework (whole-loan approach).

Pipeline position:
    Used by SACalculator._apply_risk_weights() when config.is_basel_3_1

Key responsibilities:
- LTV-band risk weight lookup for residential RE (general + income-producing)
- LTV-band risk weight lookup for commercial RE (general + income-producing)
- ADC exposure risk weight (150% / 100% pre-sold)
- Polars expression builders for vectorized lookups

References:
    - CRE20.73: Residential RE (general) whole-loan approach
    - CRE20.82: Residential RE (income-producing) whole-loan approach
    - CRE20.85: Commercial RE (general) preferential treatment
    - CRE20.86: Commercial RE (income-producing) LTV bands
    - CRE20.87-88: ADC exposures
    - PRA PS9/24 Chapter 4: UK adoption of BCBS SA risk weights
"""

from __future__ import annotations

from decimal import Decimal

import polars as pl

# =============================================================================
# RESIDENTIAL REAL ESTATE — GENERAL (CRE20.73)
# Not materially dependent on cash flows generated by the property
# Whole-loan approach (PRA PS9/24)
# =============================================================================

B31_RESIDENTIAL_GENERAL_LTV_BANDS: list[dict[str, Decimal]] = [
    {"ltv_lower": Decimal("0.00"), "ltv_upper": Decimal("0.50"), "risk_weight": Decimal("0.20")},
    {"ltv_lower": Decimal("0.50"), "ltv_upper": Decimal("0.60"), "risk_weight": Decimal("0.25")},
    {"ltv_lower": Decimal("0.60"), "ltv_upper": Decimal("0.70"), "risk_weight": Decimal("0.25")},
    {"ltv_lower": Decimal("0.70"), "ltv_upper": Decimal("0.80"), "risk_weight": Decimal("0.30")},
    {"ltv_lower": Decimal("0.80"), "ltv_upper": Decimal("0.90"), "risk_weight": Decimal("0.40")},
    {"ltv_lower": Decimal("0.90"), "ltv_upper": Decimal("1.00"), "risk_weight": Decimal("0.50")},
    {"ltv_lower": Decimal("1.00"), "ltv_upper": Decimal("999.0"), "risk_weight": Decimal("0.70")},
]

# =============================================================================
# RESIDENTIAL REAL ESTATE — INCOME-PRODUCING (CRE20.82)
# Materially dependent on cash flows generated by the property
# =============================================================================

B31_RESIDENTIAL_INCOME_LTV_BANDS: list[dict[str, Decimal]] = [
    {"ltv_lower": Decimal("0.00"), "ltv_upper": Decimal("0.50"), "risk_weight": Decimal("0.30")},
    {"ltv_lower": Decimal("0.50"), "ltv_upper": Decimal("0.60"), "risk_weight": Decimal("0.35")},
    {"ltv_lower": Decimal("0.60"), "ltv_upper": Decimal("0.70"), "risk_weight": Decimal("0.45")},
    {"ltv_lower": Decimal("0.70"), "ltv_upper": Decimal("0.80"), "risk_weight": Decimal("0.50")},
    {"ltv_lower": Decimal("0.80"), "ltv_upper": Decimal("0.90"), "risk_weight": Decimal("0.60")},
    {"ltv_lower": Decimal("0.90"), "ltv_upper": Decimal("1.00"), "risk_weight": Decimal("0.75")},
    {"ltv_lower": Decimal("1.00"), "ltv_upper": Decimal("999.0"), "risk_weight": Decimal("1.05")},
]

# =============================================================================
# COMMERCIAL REAL ESTATE — INCOME-PRODUCING (CRE20.86)
# Materially dependent on cash flows generated by the property
# =============================================================================

B31_COMMERCIAL_INCOME_LTV_BANDS: list[dict[str, Decimal]] = [
    {"ltv_lower": Decimal("0.00"), "ltv_upper": Decimal("0.60"), "risk_weight": Decimal("0.70")},
    {"ltv_lower": Decimal("0.60"), "ltv_upper": Decimal("0.80"), "risk_weight": Decimal("0.90")},
    {"ltv_lower": Decimal("0.80"), "ltv_upper": Decimal("999.0"), "risk_weight": Decimal("1.10")},
]

# =============================================================================
# COMMERCIAL REAL ESTATE — GENERAL (CRE20.85)
# Not materially dependent on cash flows
# Preferential treatment: min(60%, counterparty RW) if LTV ≤ 60%
# =============================================================================

B31_COMMERCIAL_GENERAL_LTV_THRESHOLD = Decimal("0.60")
B31_COMMERCIAL_GENERAL_PREFERENTIAL_CAP = Decimal("0.60")

# =============================================================================
# ADC EXPOSURES (CRE20.87-88)
# =============================================================================

B31_ADC_RISK_WEIGHT = Decimal("1.50")
B31_ADC_PRESOLD_RISK_WEIGHT = Decimal("1.00")


# =============================================================================
# POLARS EXPRESSION BUILDERS
# =============================================================================


def b31_residential_rw_expr() -> pl.Expr:
    """
    Polars expression for Basel 3.1 residential RE risk weights (whole-loan).

    Branches on has_income_cover to select general vs income-producing table.

    Requires columns: ltv (Float64), has_income_cover (Boolean)

    Returns:
        Expression resolving to the LTV-band risk weight
    """
    ltv = pl.col("ltv").fill_null(1.0)
    is_income = pl.col("has_income_cover").fill_null(False)

    # General residential (CRE20.73)
    general = (
        pl.when(ltv <= 0.50)
        .then(pl.lit(0.20))
        .when(ltv <= 0.60)
        .then(pl.lit(0.25))
        .when(ltv <= 0.70)
        .then(pl.lit(0.25))
        .when(ltv <= 0.80)
        .then(pl.lit(0.30))
        .when(ltv <= 0.90)
        .then(pl.lit(0.40))
        .when(ltv <= 1.00)
        .then(pl.lit(0.50))
        .otherwise(pl.lit(0.70))
    )

    # Income-producing residential (CRE20.82)
    income = (
        pl.when(ltv <= 0.50)
        .then(pl.lit(0.30))
        .when(ltv <= 0.60)
        .then(pl.lit(0.35))
        .when(ltv <= 0.70)
        .then(pl.lit(0.45))
        .when(ltv <= 0.80)
        .then(pl.lit(0.50))
        .when(ltv <= 0.90)
        .then(pl.lit(0.60))
        .when(ltv <= 1.00)
        .then(pl.lit(0.75))
        .otherwise(pl.lit(1.05))
    )

    return pl.when(is_income).then(income).otherwise(general)


def b31_commercial_rw_expr(counterparty_rw_col: str = "_cqs_risk_weight") -> pl.Expr:
    """
    Polars expression for Basel 3.1 commercial RE risk weights (whole-loan).

    General CRE (CRE20.85): min(60%, counterparty RW) if LTV ≤ 60%, else counterparty RW.
    Income-producing CRE (CRE20.86): LTV-band risk weights 70%/90%/110%.

    Requires columns: ltv, has_income_cover, and the counterparty RW column

    Args:
        counterparty_rw_col: Column containing the CQS-based counterparty risk weight

    Returns:
        Expression resolving to the risk weight
    """
    ltv = pl.col("ltv").fill_null(1.0)
    is_income = pl.col("has_income_cover").fill_null(False)
    cp_rw = pl.col(counterparty_rw_col).fill_null(1.0)

    # Income-producing CRE (CRE20.86)
    income = (
        pl.when(ltv <= 0.60)
        .then(pl.lit(0.70))
        .when(ltv <= 0.80)
        .then(pl.lit(0.90))
        .otherwise(pl.lit(1.10))
    )

    # General CRE (CRE20.85): preferential if LTV ≤ 60%
    general = pl.when(ltv <= 0.60).then(pl.min_horizontal(pl.lit(0.60), cp_rw)).otherwise(cp_rw)

    return pl.when(is_income).then(income).otherwise(general)


def b31_adc_rw_expr() -> pl.Expr:
    """
    Polars expression for Basel 3.1 ADC risk weights (CRE20.87-88).

    - 150% for ADC exposures
    - 100% if pre-sold/pre-let to qualifying buyer

    Requires columns: is_presold (Boolean)

    Returns:
        Expression resolving to 1.50 or 1.00
    """
    return pl.when(pl.col("is_presold").fill_null(False)).then(pl.lit(1.00)).otherwise(pl.lit(1.50))


# =============================================================================
# SCALAR LOOKUP FUNCTIONS (for single-exposure convenience)
# =============================================================================


def lookup_b31_residential_rw(
    ltv: Decimal,
    is_income_producing: bool = False,
) -> tuple[Decimal, str]:
    """
    Look up Basel 3.1 residential RE risk weight for a single exposure.

    Args:
        ltv: Loan-to-value ratio
        is_income_producing: Whether materially dependent on property cash flows

    Returns:
        Tuple of (risk_weight, description)
    """
    bands = (
        B31_RESIDENTIAL_INCOME_LTV_BANDS
        if is_income_producing
        else B31_RESIDENTIAL_GENERAL_LTV_BANDS
    )
    label = "income-producing" if is_income_producing else "general"

    for band in bands:
        if ltv <= band["ltv_upper"]:
            rw = band["risk_weight"]
            return rw, f"B31 RRE ({label}): {float(rw):.0%} (LTV {float(ltv):.0%})"

    rw = bands[-1]["risk_weight"]
    return rw, f"B31 RRE ({label}): {float(rw):.0%} (LTV > 100%)"


def lookup_b31_commercial_rw(
    ltv: Decimal,
    counterparty_rw: Decimal = Decimal("1.00"),
    is_income_producing: bool = False,
) -> tuple[Decimal, str]:
    """
    Look up Basel 3.1 commercial RE risk weight for a single exposure.

    Args:
        ltv: Loan-to-value ratio
        counterparty_rw: CQS-based risk weight of the counterparty (for general CRE)
        is_income_producing: Whether materially dependent on property cash flows

    Returns:
        Tuple of (risk_weight, description)
    """
    if is_income_producing:
        for band in B31_COMMERCIAL_INCOME_LTV_BANDS:
            if ltv <= band["ltv_upper"]:
                rw = band["risk_weight"]
                return rw, f"B31 CRE (income-producing): {float(rw):.0%} (LTV {float(ltv):.0%})"
        rw = B31_COMMERCIAL_INCOME_LTV_BANDS[-1]["risk_weight"]
        return rw, f"B31 CRE (income-producing): {float(rw):.0%} (LTV > 80%)"

    # General CRE (CRE20.85)
    if ltv <= B31_COMMERCIAL_GENERAL_LTV_THRESHOLD:
        rw = min(B31_COMMERCIAL_GENERAL_PREFERENTIAL_CAP, counterparty_rw)
        return rw, f"B31 CRE (general): {float(rw):.0%} (LTV {float(ltv):.0%})"

    return (
        counterparty_rw,
        f"B31 CRE (general): {float(counterparty_rw):.0%} (LTV {float(ltv):.0%} > 60%)",
    )
