"""
Basel 3.1 SA risk weight tables (PRA PS1/26 / BCBS CRE20).

Provides LTV-band based risk weight tables for real estate exposures,
ADC treatment, revised CQS-based risk weights, SCRA institution weights,
investment-grade corporate treatment, and subordinated debt treatment
under the Basel 3.1 framework.

Pipeline position:
    Used by SACalculator._apply_risk_weights() when config.is_basel_3_1

Key responsibilities:
- LTV-band risk weight lookup for residential RE (general + income-producing)
- LTV-band risk weight lookup for commercial RE (general + income-producing)
- ADC exposure risk weight (150% / 100% pre-sold)
- Revised CQS-based corporate risk weights (CQS3: 75%, CQS5: 100%)
- SCRA-based institution risk weights for unrated exposures (Grade A/B/C)
- Investment-grade corporate treatment (65%)
- SME corporate treatment (85%)
- Subordinated debt treatment (150% flat)
- Polars expression builders for vectorized lookups

References:
    - CRE20.7-15: Sovereign risk weights (unchanged from CRR)
    - CRE20.16-21: Institution risk weights (ECRA rated + SCRA unrated)
    - CRE20.22-26: Corporate risk weights (revised CQS, investment-grade, SME)
    - CRE20.47: Subordinated debt (150% flat)
    - CRE20.73: Residential RE (general) whole-loan approach
    - CRE20.82: Residential RE (income-producing) whole-loan approach
    - CRE20.85: Commercial RE (general) preferential treatment
    - CRE20.86: Commercial RE (income-producing) LTV bands
    - CRE20.87-88: ADC exposures
    - PRA PS1/26 Chapter 4: UK adoption of BCBS SA risk weights
"""

from __future__ import annotations

from decimal import Decimal

import polars as pl

# =============================================================================
# RESIDENTIAL REAL ESTATE — GENERAL (PRA PS1/26 Art. 124F)
# Not materially dependent on cash flows generated by the property
# Loan-splitting approach: 20% on secured portion (up to 55% of property value),
# counterparty risk weight on the residual (per Art. 124L)
#
# NOTE: The PRA adopted loan-splitting, NOT the BCBS CRE20.73 whole-loan table.
# Junior charges (Art. 124F(2)) reduce the 55% threshold but are not yet modelled.
# =============================================================================

B31_RESIDENTIAL_GENERAL_SECURED_RW = Decimal("0.20")
B31_RESIDENTIAL_GENERAL_MAX_SECURED_RATIO = Decimal("0.55")  # 55% of property value

# =============================================================================
# RESIDENTIAL REAL ESTATE — INCOME-PRODUCING (PRA PS1/26 Art. 124G, Table 6B)
# Materially dependent on cash flows generated by the property
# Whole-loan approach — risk weight applies to the entirety of the exposure
# =============================================================================

B31_RESIDENTIAL_INCOME_LTV_BANDS: list[dict[str, Decimal]] = [
    {"ltv_lower": Decimal("0.00"), "ltv_upper": Decimal("0.50"), "risk_weight": Decimal("0.30")},
    {"ltv_lower": Decimal("0.50"), "ltv_upper": Decimal("0.60"), "risk_weight": Decimal("0.35")},
    {"ltv_lower": Decimal("0.60"), "ltv_upper": Decimal("0.70"), "risk_weight": Decimal("0.40")},
    {"ltv_lower": Decimal("0.70"), "ltv_upper": Decimal("0.80"), "risk_weight": Decimal("0.50")},
    {"ltv_lower": Decimal("0.80"), "ltv_upper": Decimal("0.90"), "risk_weight": Decimal("0.60")},
    {"ltv_lower": Decimal("0.90"), "ltv_upper": Decimal("1.00"), "risk_weight": Decimal("0.75")},
    {"ltv_lower": Decimal("1.00"), "ltv_upper": Decimal("999.0"), "risk_weight": Decimal("1.05")},
]

# =============================================================================
# COMMERCIAL REAL ESTATE — INCOME-PRODUCING (PRA PS1/26 Art. 124I)
# Materially dependent on cash flows generated by the property
# PRA uses 2 bands (≤80%/100%, >80%/110%), NOT the BCBS CRE20.86 3-band table.
# =============================================================================

B31_COMMERCIAL_INCOME_LTV_BANDS: list[dict[str, Decimal]] = [
    {"ltv_lower": Decimal("0.00"), "ltv_upper": Decimal("0.80"), "risk_weight": Decimal("1.00")},
    {"ltv_lower": Decimal("0.80"), "ltv_upper": Decimal("999.0"), "risk_weight": Decimal("1.10")},
]

# =============================================================================
# COMMERCIAL REAL ESTATE — GENERAL (PRA PS1/26 Art. 124H)
# Not materially dependent on cash flows
# Loan-splitting: 60% on portion up to 55% of property value,
# counterparty RW on the residual (for natural person / SME)
# Other counterparties: max(60%, min(counterparty RW, Art 124I RW))
#
# NOTE: The PRA adopted loan-splitting for CRE (Art. 124H), NOT the BCBS
# CRE20.85 preferential min(60%, counterparty RW) approach.
# =============================================================================

B31_COMMERCIAL_GENERAL_SECURED_RW = Decimal("0.60")
B31_COMMERCIAL_GENERAL_MAX_SECURED_RATIO = Decimal("0.55")  # 55% of property value

# =============================================================================
# ADC EXPOSURES (CRE20.87-88)
# =============================================================================

B31_ADC_RISK_WEIGHT = Decimal("1.50")
B31_ADC_PRESOLD_RISK_WEIGHT = Decimal("1.00")

# =============================================================================
# CORPORATE CQS-BASED RISK WEIGHTS — BASEL 3.1 (PRA PS1/26 Art. 122(2) Table 6)
# Differs from CRR: CQS3 = 75% (was 100%). PRA retains CQS5 = 150% (BCBS: 100%).
# =============================================================================

B31_CORPORATE_RISK_WEIGHTS: dict[int | None, Decimal] = {
    1: Decimal("0.20"),  # AAA to AA-
    2: Decimal("0.50"),  # A+ to A-
    3: Decimal("0.75"),  # BBB+ to BBB- (CRR: 100%)
    4: Decimal("1.00"),  # BB+ to BB-
    5: Decimal("1.50"),  # B+ to B- (PRA retains 150%, BCBS reduced to 100%)
    6: Decimal("1.50"),  # CCC+ and below
    None: Decimal("1.00"),  # Unrated
}

# Investment-grade corporate: 65% (PRA PS1/26 Art. 122(6)(a))
# Qualifying: publicly traded + investment grade external rating
# Only applies when institution has PRA permission to use IG assessment
B31_CORPORATE_INVESTMENT_GRADE_RW = Decimal("0.65")

# Non-investment-grade corporate: 135% (PRA PS1/26 Art. 122(6)(b))
# Applies to unrated corporates that do NOT qualify as investment-grade
# when the institution has elected to use the IG assessment permission.
# Without IG assessment permission, all unrated corporates get 100%.
B31_CORPORATE_NON_INVESTMENT_GRADE_RW = Decimal("1.35")

# SME corporate: 85% (CRE20.47)
# Qualifying: turnover <= EUR 50m, unrated
B31_CORPORATE_SME_RW = Decimal("0.85")

# =============================================================================
# SCRA-BASED INSTITUTION RISK WEIGHTS — BASEL 3.1 (CRE20.16-21)
# Standardised Credit Risk Assessment Approach for unrated institutions.
# Replaces CRR due-diligence assessment for unrated.
# Rated institutions use ECRA (same as CRR Art. 120-121).
# =============================================================================

B31_SCRA_RISK_WEIGHTS: dict[str, Decimal] = {
    "A": Decimal("0.40"),  # CET1 > 14%, Leverage > 5%, meets all requirements
    "B": Decimal("0.75"),  # CET1 > 5.5%, Leverage > 3%, meets minimums
    "C": Decimal("1.50"),  # Below minimum requirements
}

# =============================================================================
# RETAIL TRANSACTOR RISK WEIGHT — BASEL 3.1 (PRA PS1/26 Art. 123)
# Qualifying revolving retail exposures where obligor repays in full each period
# =============================================================================

B31_RETAIL_TRANSACTOR_RW = Decimal("0.45")  # 45% for QRRE transactors
B31_RETAIL_NON_REGULATORY_RW = Decimal("1.00")  # 100% for non-regulatory retail (Art. 123(3)(c))

# =============================================================================
# SA SPECIALISED LENDING — BASEL 3.1 (PRA PS1/26 Art. 122A-122B)
# New SA exposure class with risk weights distinct from general corporates.
# Rated SL exposures use the corporate CQS table (Art. 122A(3)).
# =============================================================================

B31_SA_SL_RISK_WEIGHTS: dict[str, Decimal] = {
    "object_finance": Decimal("1.00"),  # 100%
    "commodities_finance": Decimal("1.00"),  # 100%
    "project_finance_pre_operational": Decimal("1.30"),  # 130%
    "project_finance_operational": Decimal("1.00"),  # 100%
    "project_finance_high_quality": Decimal("0.80"),  # 80%
}

# =============================================================================
# SUBORDINATED DEBT RISK WEIGHT — BASEL 3.1 (CRE20.49)
# Flat 150% for all subordinated debt (institution + corporate)
# =============================================================================

B31_SUBORDINATED_DEBT_RW = Decimal("1.50")

# =============================================================================
# DEFAULTED EXPOSURE RISK WEIGHTS — BASEL 3.1 (CRE20.88-90)
# =============================================================================

B31_DEFAULTED_RW_HIGH_PROVISION = Decimal("1.00")  # Art. 127: provisions >= 20%
B31_DEFAULTED_RW_LOW_PROVISION = Decimal("1.50")  # Art. 127: provisions < 20%
B31_DEFAULTED_PROVISION_THRESHOLD = Decimal("0.20")  # PRA PS1/26 Art. 127: 20% threshold


def _create_b31_corporate_df() -> pl.DataFrame:
    """Create Basel 3.1 corporate risk weight lookup DataFrame."""
    return pl.DataFrame(
        {
            "cqs": [1, 2, 3, 4, 5, 6, None],
            "risk_weight": [0.20, 0.50, 0.75, 1.00, 1.50, 1.50, 1.00],
            "exposure_class": ["CORPORATE"] * 7,
        }
    ).with_columns(
        [
            pl.col("cqs").cast(pl.Int8),
            pl.col("risk_weight").cast(pl.Float64),
        ]
    )


def get_b31_combined_cqs_risk_weights(use_uk_deviation: bool = True) -> pl.DataFrame:
    """
    Get combined CQS-based risk weight table for Basel 3.1 joins.

    Uses Basel 3.1 corporate weights (CQS3=75%, CQS5=100%) while
    sovereign and institution ECRA weights remain the same as CRR.

    Args:
        use_uk_deviation: Whether to use UK-specific institution weights

    Returns:
        Combined DataFrame with columns: exposure_class, cqs, risk_weight
    """
    from rwa_calc.data.tables.crr_risk_weights import (
        _create_cgcb_df,
        _create_covered_bond_df,
        _create_institution_df,
        _create_pse_df,
        _create_rgla_df,
    )

    return pl.concat(
        [
            _create_cgcb_df().select(["exposure_class", "cqs", "risk_weight"]),
            _create_rgla_df().select(["exposure_class", "cqs", "risk_weight"]),
            _create_pse_df().select(["exposure_class", "cqs", "risk_weight"]),
            _create_institution_df(use_uk_deviation).select(
                ["exposure_class", "cqs", "risk_weight"]
            ),
            _create_b31_corporate_df().select(["exposure_class", "cqs", "risk_weight"]),
            _create_covered_bond_df().select(["exposure_class", "cqs", "risk_weight"]),
        ]
    )


# =============================================================================
# POLARS EXPRESSION BUILDERS
# =============================================================================


def b31_residential_rw_expr(
    counterparty_rw_col: str = "_cqs_risk_weight",
) -> pl.Expr:
    """
    Polars expression for Basel 3.1 residential RE risk weights.

    General residential (Art. 124F): Loan-splitting approach — 20% on the
    secured portion (up to 55% of property value), counterparty RW on the
    residual. Produces a weighted-average RW for the whole exposure.

    Income-producing residential (Art. 124G, Table 6B): Whole-loan approach
    with LTV-band risk weights applied to the entire exposure.

    Requires columns: ltv (Float64), has_income_cover (Boolean),
        and the counterparty RW column (Float64)

    Args:
        counterparty_rw_col: Column containing the counterparty risk weight
            (per Art. 124L: 75% for individuals, 85% for non-retail SME,
            or the unsecured corporate RW)

    Returns:
        Expression resolving to the risk weight
    """
    ltv = pl.col("ltv").fill_null(1.0)
    is_income = pl.col("has_income_cover").fill_null(False)
    cp_rw = pl.col(counterparty_rw_col).fill_null(0.75)

    # General residential (PRA PS1/26 Art. 124F) — loan-splitting
    # secured_share = min(1.0, 0.55 / ltv) — portion at 20% secured RW
    # residual at counterparty RW (Art. 124L: 75% for individuals/retail SME)
    # For residential mortgages, the CQS-based RW may be null (unrated retail)
    # so we default to 75% per Art. 124L(a)
    cp_rw_for_rre = pl.when(cp_rw >= 1.0).then(pl.lit(0.75)).otherwise(cp_rw)
    secured_share = pl.min_horizontal(pl.lit(1.0), pl.lit(0.55) / ltv)
    general = pl.lit(0.20) * secured_share + cp_rw_for_rre * (pl.lit(1.0) - secured_share)

    # Income-producing residential (PRA PS1/26 Art. 124G, Table 6B)
    income = (
        pl.when(ltv <= 0.50)
        .then(pl.lit(0.30))
        .when(ltv <= 0.60)
        .then(pl.lit(0.35))
        .when(ltv <= 0.70)
        .then(pl.lit(0.40))
        .when(ltv <= 0.80)
        .then(pl.lit(0.50))
        .when(ltv <= 0.90)
        .then(pl.lit(0.60))
        .when(ltv <= 1.00)
        .then(pl.lit(0.75))
        .otherwise(pl.lit(1.05))
    )

    return pl.when(is_income).then(income).otherwise(general)


def b31_commercial_rw_expr(counterparty_rw_col: str = "_cqs_risk_weight") -> pl.Expr:
    """
    Polars expression for Basel 3.1 commercial RE risk weights.

    General CRE (PRA Art. 124H): Loan-splitting — 60% on portion up to 55% of
    property value, counterparty RW on the residual.
    Income-producing CRE (PRA Art. 124I): 100% (LTV ≤ 80%), 110% (LTV > 80%).

    Requires columns: ltv, has_income_cover, and the counterparty RW column

    Args:
        counterparty_rw_col: Column containing the CQS-based counterparty risk weight

    Returns:
        Expression resolving to the risk weight
    """
    ltv = pl.col("ltv").fill_null(1.0)
    is_income = pl.col("has_income_cover").fill_null(False)
    cp_rw = pl.col(counterparty_rw_col).fill_null(1.0)

    # Income-producing CRE (PRA Art. 124I): 100% ≤80% LTV, 110% >80% LTV
    income = pl.when(ltv <= 0.80).then(pl.lit(1.00)).otherwise(pl.lit(1.10))

    # General CRE (PRA Art. 124H): loan-splitting at 55% of property value
    # secured_share = min(1.0, 0.55 / LTV)
    # RW = 0.60 × secured_share + counterparty_RW × (1.0 - secured_share)
    secured_share = pl.min_horizontal(pl.lit(1.0), pl.lit(0.55) / ltv)
    general = pl.lit(0.60) * secured_share + cp_rw * (pl.lit(1.0) - secured_share)

    return pl.when(is_income).then(income).otherwise(general)


def b31_adc_rw_expr() -> pl.Expr:
    """
    Polars expression for Basel 3.1 ADC risk weights (CRE20.87-88).

    - 150% for ADC exposures
    - 100% if pre-sold/pre-let to qualifying buyer

    Requires columns: is_presold (Boolean)

    Returns:
        Expression resolving to 1.50 or 1.00
    """
    return pl.when(pl.col("is_presold").fill_null(False)).then(pl.lit(1.00)).otherwise(pl.lit(1.50))


def b31_sa_sl_rw_expr() -> pl.Expr:
    """
    Polars expression for Basel 3.1 SA specialised lending risk weights.

    PRA PS1/26 Art. 122A-122B. Unrated SL exposures get type-specific risk
    weights rather than falling through to corporate 100%.

    Requires columns: sl_type (String), sl_project_phase (String, optional)

    Returns:
        Expression resolving to the SL-specific risk weight
    """
    sl = pl.col("sl_type").fill_null("").str.to_lowercase()
    phase = pl.col("sl_project_phase").fill_null("").str.to_lowercase()

    return (
        pl.when(sl.str.contains("object"))
        .then(pl.lit(1.00))
        .when(sl.str.contains("commodit"))
        .then(pl.lit(1.00))
        .when(sl.str.contains("project"))
        .then(
            pl.when(phase.str.contains("pre"))
            .then(pl.lit(1.30))
            .when(phase.str.contains("high"))
            .then(pl.lit(0.80))
            .otherwise(pl.lit(1.00))  # operational default
        )
        .otherwise(pl.lit(1.00))  # fallback for unknown SL types
    )


# =============================================================================
# SCALAR LOOKUP FUNCTIONS (for single-exposure convenience)
# =============================================================================


def lookup_b31_residential_rw(
    ltv: Decimal,
    is_income_producing: bool = False,
    counterparty_rw: Decimal = Decimal("0.75"),
) -> tuple[Decimal, str]:
    """
    Look up Basel 3.1 residential RE risk weight for a single exposure.

    General residential uses loan-splitting (Art. 124F): 20% on portion up to
    55% of property value, counterparty RW on the residual.

    Income-producing uses Table 6B LTV bands (Art. 124G).

    Args:
        ltv: Loan-to-value ratio
        is_income_producing: Whether materially dependent on property cash flows
        counterparty_rw: Counterparty risk weight for general residential
            loan-splitting (default 75% for individuals per Art. 124L)

    Returns:
        Tuple of (risk_weight, description)
    """
    if is_income_producing:
        for band in B31_RESIDENTIAL_INCOME_LTV_BANDS:
            if ltv <= band["ltv_upper"]:
                rw = band["risk_weight"]
                return rw, f"B31 RRE (income-producing): {float(rw):.0%} (LTV {float(ltv):.0%})"
        rw = B31_RESIDENTIAL_INCOME_LTV_BANDS[-1]["risk_weight"]
        return rw, f"B31 RRE (income-producing): {float(rw):.0%} (LTV > 100%)"

    # General residential — loan-splitting (PRA PS1/26 Art. 124F)
    secured_ratio = min(Decimal("1.0"), B31_RESIDENTIAL_GENERAL_MAX_SECURED_RATIO / ltv)
    rw = B31_RESIDENTIAL_GENERAL_SECURED_RW * secured_ratio + counterparty_rw * (
        Decimal("1.0") - secured_ratio
    )
    return rw, (
        f"B31 RRE (general, loan-split): {float(rw):.1%} "
        f"(LTV {float(ltv):.0%}, secured {float(secured_ratio):.0%} @ 20%, "
        f"residual @ {float(counterparty_rw):.0%})"
    )


def lookup_b31_commercial_rw(
    ltv: Decimal,
    counterparty_rw: Decimal = Decimal("1.00"),
    is_income_producing: bool = False,
) -> tuple[Decimal, str]:
    """
    Look up Basel 3.1 commercial RE risk weight for a single exposure.

    Args:
        ltv: Loan-to-value ratio
        counterparty_rw: CQS-based risk weight of the counterparty (for general CRE)
        is_income_producing: Whether materially dependent on property cash flows

    Returns:
        Tuple of (risk_weight, description)
    """
    if is_income_producing:
        for band in B31_COMMERCIAL_INCOME_LTV_BANDS:
            if ltv <= band["ltv_upper"]:
                rw = band["risk_weight"]
                return rw, f"B31 CRE (income-producing): {float(rw):.0%} (LTV {float(ltv):.0%})"
        rw = B31_COMMERCIAL_INCOME_LTV_BANDS[-1]["risk_weight"]
        return rw, f"B31 CRE (income-producing): {float(rw):.0%} (LTV > 80%)"

    # General CRE (PRA Art. 124H) — loan-splitting at 55% of property value
    secured_ratio = min(Decimal("1.0"), B31_COMMERCIAL_GENERAL_MAX_SECURED_RATIO / ltv)
    rw = B31_COMMERCIAL_GENERAL_SECURED_RW * secured_ratio + counterparty_rw * (
        Decimal("1.0") - secured_ratio
    )
    return rw, (
        f"B31 CRE (general, loan-split): {float(rw):.1%} "
        f"(LTV {float(ltv):.0%}, secured {float(secured_ratio):.0%} @ 60%, "
        f"residual @ {float(counterparty_rw):.0%})"
    )
