"""Regenerate citation-coverage artefacts from live ``@cites`` annotations.

Two outputs, kept in sync by a single command:

1. ``docs/development/citation-matrix.md`` — invokes ``watchfire matrix
   --format json`` once per indexed instrument (CRR, PS1/26), then builds an
   article-grouped page with click-to-expand ``??? quote`` collapsibles
   containing ``pymdownx.snippets`` directives that pull the live function
   source from disk at Zensical build time.
2. ``tests/contracts/data/citation_snapshot.json`` — a machine-readable
   snapshot mapping ``"module::attr_path"`` to the canonical citation list
   each decorated function carries (outermost decorator first).
   ``tests/contracts/test_watchfire_coverage.py`` diffs the live tree
   against this snapshot so citation coverage can never silently shrink.

Usage:
    uv run python scripts/generate_citation_matrix.py                  # both outputs
    uv run python scripts/generate_citation_matrix.py --snapshot-only  # snapshot only

Exit codes:
    0 = artefacts regenerated successfully
    1 = watchfire matrix invocation failed
"""

from __future__ import annotations

import argparse
import ast
import importlib
import json
import subprocess
import sys
from collections.abc import Iterator
from datetime import date
from functools import cache
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_ROOT = REPO_ROOT / "src"
OUTPUT_PATH = REPO_ROOT / "docs" / "development" / "citation-matrix.md"
SNAPSHOT_PATH = REPO_ROOT / "tests" / "contracts" / "data" / "citation_snapshot.json"


PREAMBLE = """# Citation Coverage Matrix

This page is generated by ``scripts/generate_citation_matrix.py`` from the
live ``@cites(...)`` decorators in ``src/rwa_calc/``. Each heading is one
regulatory article; expand a function below it to read the implementation
inline. See [citation-tracking.md](citation-tracking.md) for the
conventions and canonical citation grammar.

Regenerate after annotation changes:

```bash
uv run python scripts/generate_citation_matrix.py
```

Last generated: {generated_on}.

"""

INSTRUMENTS: list[tuple[str, str]] = [
    ("CRR", "CRR (Capital Requirements Regulation)"),
    ("PS", "PS1/26 (PRA Policy Statement)"),
]

# CRR articles to render densely in numerical order. Each entry in this tuple
# MUST be resolvable to either (a) one or more decorated functions in the live
# watchfire matrix, or (b) a row in ``CRR_COVERAGE_NOTES`` explaining why it is
# deliberately not cited. Articles outside this range render sparsely (only
# those with ``@cites`` decorators).
CRR_DENSE_RANGE: tuple[str, ...] = (
    "111",
    "112",
    "113",
    "114",
    "115",
    "116",
    "117",
    "118",
    "119",
    "120",
    "121",
    "122",
    "123",
    "124",
    "125",
    "126",
    "127",
    "128",
    "129",
    "130",
    "131",
    "132",
    "133",
    "134",
    "135",
    "136",
    "137",
    "138",
    "139",
    "140",
    "141",
    "142",
    "143",
    "144",
    "145",
    "146",
    "147",
    "147A",
    "148",
    "149",
    "150",
    "151",
    "152",
)

# CRR articles in ``CRR_DENSE_RANGE`` that are deliberately not cited. Each row
# is ``(title, reason_markdown)``. The renderer emits these as italic
# "Out of scope" blocks alongside the implemented articles, so readers see a
# complete picture of the CRR Title II range without leaving the page.
CRR_COVERAGE_NOTES: dict[str, tuple[str, str]] = {
    "128": (
        "Items associated with particular high risk",
        "UK CRR omitted Art. 128 by SI 2021/1078 reg. 6(3)(a) "
        "(effective 1 Jan 2022) — exposures that would have attracted 150% "
        "fall through to the 100% OTHER class under UK CRR. "
        "The 150% treatment is reintroduced under Basel 3.1 — see "
        "`PS1/26, paragraph 128` for the live decorator on "
        "`engine/sa/namespace.py::_b31_append_high_risk_branch`.",
    ),
    "130": (
        "Items representing securitisation positions",
        "Out of scope — securitisation is handled by a separate "
        "calculator domain (CRR Title II, Chapter 5). This calculator covers "
        "Chapters 1-4 only.",
    ),
    "132": (
        "Exposures in the form of units or shares in collective investment undertakings (CIUs)",
        "UK CRR omitted Art. 132; PRA reintroduced CIU treatment via "
        "PS1/26 paragraph 132. Implementation lives at "
        "`engine/equity/calculator.py::_append_ciu_branches` and is cited "
        "under `PS1/26, paragraph 132` in the PS1/26 section below.",
    ),
    "142": (
        "Definitions for the IRB approach",
        "Definitions only — no calculation path. The terms are realised "
        "in `src/rwa_calc/domain/enums.py` (e.g. `ExposureClass`, "
        "`ApproachType`) and `src/rwa_calc/data/schemas.py`.",
    ),
    "144": (
        "Competent authorities' assessment of an application",
        "Supervisory process — out of scope for a calculator. IRB "
        "permissions enter the engine via the `model_permissions` input "
        "table; the calculator trusts whatever rows the firm supplies.",
    ),
    "145": (
        "Prior experience with IRB approaches",
        "Supervisory process — out of scope. Prior-experience review is "
        "tracked in supervisory records, not in calculator state.",
    ),
    "146": (
        "Measures to be taken where requirements cease to be met",
        "Supervisory revocation — out of scope. Revocation is realised "
        "operationally by removing rows from the `model_permissions` input.",
    ),
    "147A": (
        "IRB approach restrictions (Basel 3.1)",
        "Implemented in `engine/classifier.py::_apply_b31_approach_"
        "restrictions`. CRR-side decoration is deferred — Art. 147A is a "
        "Basel 3.1 amendment with no original CRR equivalent, and watchfire's "
        "bundled CRR index does not cover the `A` suffix (see "
        "[citation-tracking.md](citation-tracking.md) on alphanumeric "
        "article handling). The PS1/26 paragraph mapping is pending a "
        "future review.",
    ),
    "149": (
        "Conditions for reverting to the use of less sophisticated approaches",
        "Supervisory process — out of scope. Reversion is realised "
        "operationally via removal of permission rows; the calculator "
        "automatically falls back to SA when no IRB permission matches.",
    ),
    "152": (
        "Treatment of exposures in the form of CIU units (IRB)",
        "Not implemented — CIU look-through under IRB is out of scope for "
        "this calculator. Equity-class CIU treatment under SA is in scope "
        "via `engine/equity/calculator.py::_append_ciu_branches` "
        "(see `PS1/26, paragraph 132`).",
    ),
}


@cache
def _parse(file_path: Path) -> ast.Module:
    """Parse a file once and cache the AST tree."""
    return ast.parse(file_path.read_text(encoding="utf-8"))


def function_range(file_path: Path, site_line: int) -> tuple[int, int]:
    """Return ``(start_line, end_line)`` for the function whose decorator chain
    or ``def`` line includes ``site_line``.

    The watchfire JSON ``line`` field reports the line of the ``@cites(...)``
    decorator that produced the citation. For stacked-decorator functions a
    single function definition surfaces as multiple sites at different
    decorator lines, so the matcher accepts any of:
      - ``node.lineno`` (the ``def`` line), or
      - the line of any decorator in ``node.decorator_list``.

    ``start_line`` is always the topmost decorator (inclusive) so the snippet
    shows the full ``@cites(...)`` chain alongside the function body.
    ``end_line`` is ``node.end_lineno`` (last body line, inclusive).
    """
    tree = _parse(file_path)
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            decorator_lines = {d.lineno for d in node.decorator_list}
            if site_line == node.lineno or site_line in decorator_lines:
                start = min(
                    (d.lineno for d in node.decorator_list),
                    default=node.lineno,
                )
                end = node.end_lineno or node.lineno
                return start, end
    raise LookupError(f"no function definition at {file_path}:{site_line}")


def _run_matrix_json(instrument: str) -> dict[str, Any]:
    """Invoke ``watchfire matrix --instrument <X> --format json``."""
    result = subprocess.run(
        [
            "uv",
            "run",
            "watchfire",
            "matrix",
            "--instrument",
            instrument,
            "--format",
            "json",
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        sys.stderr.write(
            f"watchfire matrix --instrument {instrument} exited "
            f"{result.returncode}\n{result.stderr}\n"
        )
        sys.exit(1)
    return json.loads(result.stdout)


def _render_site(site: dict[str, Any], warnings: list[str]) -> str:
    """Render one ``??? quote`` block containing a snippet directive.

    On AST-lookup failure, fall back to a fixed ±20-line window so the
    page still renders, and record a warning for the bottom of the page.
    """
    rel_path = site["file"]
    def_line = int(site["line"])
    func_name = site["function"]

    abs_path = REPO_ROOT / rel_path
    try:
        start, end = function_range(abs_path, def_line)
    except LookupError as exc:
        warnings.append(f"- `{rel_path}:{def_line}` ({func_name}): {exc}")
        start = max(1, def_line - 1)
        end = def_line + 20

    return (
        f'??? quote "`{func_name}` — {rel_path}:{def_line}"\n'
        f"    ```python\n"
        f'    --8<-- "{rel_path}:{start}:{end}"\n'
        f"    ```\n"
    )


def _render_entry(entry: dict[str, Any], warnings: list[str]) -> str:
    """Render one ``### <key> — <title>`` section with one collapsible per site."""
    title = entry.get("title") or ""
    heading_suffix = f" — {title}" if title else ""
    out = [f"### {entry['key']}{heading_suffix}\n"]
    for site in entry["sites"]:
        out.append(_render_site(site, warnings))
    return "\n".join(out) + "\n"


def _render_coverage_note(article: str, title: str, reason: str) -> str:
    """Render one ``### CRR Art. <N> — <title>`` block with an italic reason.

    The ``reason`` body is emitted verbatim inside a single italic block —
    each ``CRR_COVERAGE_NOTES`` entry chooses its own framing (out-of-scope,
    UK-omitted, definitional, deferred, etc.).
    """
    return f"### CRR Art. {article} — {title}\n\n*{reason}*\n\n"


def _crr_article_key(entry_key: str) -> str | None:
    """Extract the article suffix from a watchfire key like ``CRR Art. 134``."""
    prefix = "CRR Art. "
    if entry_key.startswith(prefix):
        return entry_key[len(prefix) :].strip()
    return None


def _render_crr_section(
    section_heading: str,
    matrix: dict[str, Any],
    warnings: list[str],
) -> str:
    """Render the CRR section with the dense 111-152 range plus sparse tail.

    Every article in :data:`CRR_DENSE_RANGE` MUST resolve to either a live
    watchfire entry or a :data:`CRR_COVERAGE_NOTES` row — the renderer raises
    on omission so the matrix can never silently drop coverage. Articles
    outside the dense range render as today (sparse — only the ones with
    decorators).
    """
    entries = matrix.get("entries", [])
    by_article: dict[str, dict[str, Any]] = {}
    for entry in entries:
        article = _crr_article_key(entry["key"])
        if article is not None:
            by_article[article] = entry

    out = [f"## {section_heading}\n"]

    rendered_articles: set[str] = set()
    for article in CRR_DENSE_RANGE:
        if article in by_article:
            out.append(_render_entry(by_article[article], warnings))
            rendered_articles.add(article)
        elif article in CRR_COVERAGE_NOTES:
            title, reason = CRR_COVERAGE_NOTES[article]
            out.append(_render_coverage_note(article, title, reason))
            rendered_articles.add(article)
        else:
            raise RuntimeError(
                f"CRR Art. {article} is in CRR_DENSE_RANGE but has neither a "
                f"live @cites decorator nor a CRR_COVERAGE_NOTES entry. Add "
                f"one or remove it from the dense range."
            )

    # Sparse tail: render any articles outside the dense range in matrix order.
    for entry in entries:
        article = _crr_article_key(entry["key"])
        if article is None or article in rendered_articles:
            continue
        out.append(_render_entry(entry, warnings))

    return "\n".join(out)


def _render_instrument_section(
    section_heading: str,
    matrix: dict[str, Any],
    warnings: list[str],
) -> str:
    """Render the ``## <heading>`` section with all article subsections beneath."""
    out = [f"## {section_heading}\n"]
    entries = matrix.get("entries", [])
    if not entries:
        out.append("_No annotated functions for this instrument._\n")
        return "\n".join(out)
    for entry in entries:
        out.append(_render_entry(entry, warnings))
    return "\n".join(out)


def iter_cited_functions(src_root: Path = SRC_ROOT) -> Iterator[tuple[str, str]]:
    """Yield ``(module_path, attr_path)`` for every ``@cites``-decorated function.

    Scans module-level functions and methods of module-level classes in
    ``src/rwa_calc/`` — the same shapes the coverage test resolves at runtime
    via ``getattr`` chains. ``attr_path`` is the bare function name for
    module-level functions and ``ClassName.method`` for methods.
    """
    for py_file in sorted((src_root / "rwa_calc").rglob("*.py")):
        tree = _parse(py_file)
        module_path = _module_path_for(py_file, src_root)
        for node in tree.body:
            if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
                if _has_cites_decorator(node):
                    yield module_path, node.name
            elif isinstance(node, ast.ClassDef):
                for child in node.body:
                    if isinstance(
                        child, ast.FunctionDef | ast.AsyncFunctionDef
                    ) and _has_cites_decorator(child):
                        yield module_path, f"{node.name}.{child.name}"


def collect_citation_state(src_root: Path = SRC_ROOT) -> dict[str, list[str]]:
    """Build ``{"module::attr_path": [canonical citations]}`` from the live tree.

    Citations are listed in ``__watchfire__`` order (outermost decorator
    first, matching how watchfire builds the attribute), so the snapshot pins
    both the citation set and the decorator stacking order per function.
    """
    state: dict[str, list[str]] = {}
    for module_path, attr_path in iter_cited_functions(src_root):
        obj: Any = importlib.import_module(module_path)
        for part in attr_path.split("."):
            obj = getattr(obj, part)
        citations = getattr(obj, "__watchfire__", ())
        state[f"{module_path}::{attr_path}"] = [c.canonical() for c in citations]
    return state


def write_snapshot() -> None:
    """Write the committed citation snapshot consumed by the coverage test."""
    state = collect_citation_state()
    SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT_PATH.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {SNAPSHOT_PATH.relative_to(REPO_ROOT)} ({len(state)} functions)")


def _module_path_for(py_file: Path, src_root: Path) -> str:
    """Map ``src/rwa_calc/engine/ccf.py`` -> ``rwa_calc.engine.ccf``."""
    parts = py_file.relative_to(src_root).with_suffix("").parts
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts)


def _has_cites_decorator(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    """True if any decorator on ``node`` is ``cites(...)`` / ``watchfire.cites(...)``."""
    for decorator in node.decorator_list:
        target = decorator.func if isinstance(decorator, ast.Call) else decorator
        if isinstance(target, ast.Name) and target.id == "cites":
            return True
        if isinstance(target, ast.Attribute) and target.attr == "cites":
            return True
    return False


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--snapshot-only",
        action="store_true",
        help="write only tests/contracts/data/citation_snapshot.json (skip the docs page)",
    )
    args = parser.parse_args(argv)

    if not args.snapshot_only:
        warnings: list[str] = []
        sections: list[str] = []
        for instrument_key, section_heading in INSTRUMENTS:
            matrix = _run_matrix_json(instrument_key)
            if instrument_key == "CRR":
                sections.append(_render_crr_section(section_heading, matrix, warnings))
            else:
                sections.append(_render_instrument_section(section_heading, matrix, warnings))

        body = PREAMBLE.format(generated_on=date.today().isoformat()) + "\n".join(sections)
        if warnings:
            body += (
                "\n---\n\n"
                "## Generator warnings\n\n"
                "The following sites could not be resolved to a function definition "
                "via AST; the snippet falls back to a fixed window. Investigate and "
                "fix the underlying issue (renamed function, refactored file, etc.).\n\n"
                + "\n".join(warnings)
                + "\n"
            )

        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_PATH.write_text(body, encoding="utf-8")
        print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")

    write_snapshot()
    return 0


if __name__ == "__main__":
    sys.exit(main())
