"""Regenerate ``docs/development/module-dependencies.md`` from the live import graph.

Uses the ``curfew`` dev tool's Python API to build the first-party import graph of
``src/rwa_calc`` and renders two Mermaid charts into one docs page:

1. A **package-level overview** — first-party edges collapsed to their top-level
   package (depth-2 prefix, e.g. ``rwa_calc.engine.sa.calculator -> rwa_calc.engine``),
   giving a small, readable diagram of how the major subpackages depend on each other.
2. The **full module-level graph** — curfew's verbatim ``render_mermaid`` output, one
   node per module, tucked inside a collapsible block because it is large.

This mirrors ``scripts/generate_citation_matrix.py``: the whole page is owned by this
script, carries a "Last generated" date, and is re-run by ``scripts/deploy.py``.

Usage:
    uv run python scripts/generate_dependency_graph.py

Exit codes:
    0 = page regenerated successfully
    1 = graph build / curfew invocation failed
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

from curfew.config import load_config
from curfew.errors import CurfewError
from curfew.graph import build_graph
from curfew.model import EdgeClass, Graph
from curfew.viz.mermaid import render_mermaid

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "development" / "module-dependencies.md"

# Curfew's first-party node style, reused for the hand-built package overview so it
# matches the colours of the full module graph (blue = first-party).
FIRST_PARTY_STYLE = "fill:#e8f0fe,stroke:#1a73e8,color:#202124"

# Edge kinds that represent a real first-party -> first-party import.
_FIRST_PARTY_EDGES = (EdgeClass.FIRST_PARTY_INTRA, EdgeClass.FIRST_PARTY_CROSS)

PREAMBLE = """# Module Dependencies

This page is generated by ``scripts/generate_dependency_graph.py`` from the live
import graph of ``src/rwa_calc``, built with the [`curfew`](https://github.com/OpenAfterHours)
dependency tool. It is a snapshot of how the code actually imports itself — not a
hand-drawn design diagram.

Regenerate after structural refactors:

```bash
uv run python scripts/generate_dependency_graph.py
```

Inspect a single module's dependencies and dependents directly:

```bash
uv run curfew report rwa_calc.engine.classifier
```

Last generated: {generated_on}.
"""


def main() -> int:
    """Build the import graph and write the dependency-graph docs page."""
    try:
        graph = _build_repo_graph()
    except CurfewError as exc:
        print(f"curfew: {exc}", file=sys.stderr)
        return 1

    page = _build_page(graph)
    OUTPUT_PATH.write_text(page, encoding="utf-8")

    module_count = _first_party_module_count(graph)
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({module_count} modules).")
    return 0


def _build_repo_graph() -> Graph:
    """Build the first-party import graph for this repository (no config required)."""
    config = load_config(REPO_ROOT)
    built = build_graph(config.members, known_first_party=config.known_first_party)
    return built.graph


def _build_page(graph: Graph) -> str:
    """Assemble the full Markdown page from the preamble and both charts."""
    module_count = _first_party_module_count(graph)
    overview = _render_package_overview(graph)
    full_graph = render_mermaid(graph, direction="LR")

    sections = [
        PREAMBLE.format(generated_on=date.today().isoformat()),
        "## Package overview",
        (
            "Each node is a top-level subpackage of `rwa_calc`; an arrow `A --> B` means "
            "some module in `A` imports some module in `B`. Module-level imports are "
            "collapsed to their package here for readability."
        ),
        _fence(overview),
        "## Full module graph",
        "The complete graph, one node per module, exactly as `curfew show --mermaid` emits it.",
        _collapsible_full_graph(full_graph, module_count),
        "",
    ]
    return "\n\n".join(sections)


def _render_package_overview(graph: Graph) -> str:
    """Collapse first-party edges to their top-level package and render a Mermaid chart."""
    pkg_edges: set[tuple[str, str]] = set()
    for edge in graph.edges:
        if edge.cls not in _FIRST_PARTY_EDGES:
            continue
        src, dst = _top_level_package(edge.src), _top_level_package(edge.dst)
        if src != dst:
            pkg_edges.add((src, dst))

    packages = sorted({pkg for edge in pkg_edges for pkg in edge})
    ids = {pkg: f"p{index}" for index, pkg in enumerate(packages)}

    lines = ["flowchart LR"]
    lines.extend(f'    {ids[pkg]}["{pkg}"]' for pkg in packages)
    lines.extend(f"    {ids[src]} --> {ids[dst]}" for src, dst in sorted(pkg_edges))
    lines.append(f"    classDef first_party {FIRST_PARTY_STYLE}")
    if packages:
        lines.append(f"    class {','.join(ids[pkg] for pkg in packages)} first_party")
    return "\n".join(lines)


def _collapsible_full_graph(mermaid: str, module_count: int) -> str:
    """Wrap the full Mermaid chart in an indented ``??? note`` details block."""
    indented_fence = "\n".join(
        f"    {line}" if line else line for line in _fence(mermaid).splitlines()
    )
    return f'??? note "Full module-level graph ({module_count} modules)"\n\n{indented_fence}'


def _fence(mermaid: str) -> str:
    """Wrap a Mermaid body in a ```mermaid fenced code block."""
    return f"```mermaid\n{mermaid}\n```"


def _top_level_package(module: str) -> str:
    """Map a module id to its top-level package (depth-2 dotted prefix)."""
    return ".".join(module.split(".")[:2])


def _first_party_module_count(graph: Graph) -> int:
    """Count first-party nodes — the node set the full graph renders."""
    return sum(1 for node in graph.nodes.values() if node.member is not None)


if __name__ == "__main__":
    raise SystemExit(main())
