"""Regenerate ``docs/development/citation-matrix.md`` from live ``@cites`` annotations.

Invokes ``watchfire matrix --format json`` once per indexed instrument
(CRR, PS1/26), then builds an article-grouped page with click-to-expand
``??? quote`` collapsibles containing ``pymdownx.snippets`` directives that
pull the live function source from disk at Zensical build time.

Usage:
    uv run python scripts/generate_citation_matrix.py

Exit codes:
    0 = matrix regenerated successfully
    1 = watchfire matrix invocation failed
"""

from __future__ import annotations

import ast
import json
import subprocess
import sys
from datetime import date
from functools import cache
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "development" / "citation-matrix.md"


PREAMBLE = """# Citation Coverage Matrix

This page is generated by ``scripts/generate_citation_matrix.py`` from the
live ``@cites(...)`` decorators in ``src/rwa_calc/``. Each heading is one
regulatory article; expand a function below it to read the implementation
inline. See [citation-tracking.md](citation-tracking.md) for the
conventions and canonical citation grammar.

Regenerate after annotation changes:

```bash
uv run python scripts/generate_citation_matrix.py
```

Last generated: {generated_on}.

"""

INSTRUMENTS: list[tuple[str, str]] = [
    ("CRR", "CRR (Capital Requirements Regulation)"),
    ("PS", "PS1/26 (PRA Policy Statement)"),
]


@cache
def _parse(file_path: Path) -> ast.Module:
    """Parse a file once and cache the AST tree."""
    return ast.parse(file_path.read_text(encoding="utf-8"))


def function_range(file_path: Path, site_line: int) -> tuple[int, int]:
    """Return ``(start_line, end_line)`` for the function whose decorator chain
    or ``def`` line includes ``site_line``.

    The watchfire JSON ``line`` field reports the line of the ``@cites(...)``
    decorator that produced the citation. For stacked-decorator functions a
    single function definition surfaces as multiple sites at different
    decorator lines, so the matcher accepts any of:
      - ``node.lineno`` (the ``def`` line), or
      - the line of any decorator in ``node.decorator_list``.

    ``start_line`` is always the topmost decorator (inclusive) so the snippet
    shows the full ``@cites(...)`` chain alongside the function body.
    ``end_line`` is ``node.end_lineno`` (last body line, inclusive).
    """
    tree = _parse(file_path)
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            decorator_lines = {d.lineno for d in node.decorator_list}
            if site_line == node.lineno or site_line in decorator_lines:
                start = min(
                    (d.lineno for d in node.decorator_list),
                    default=node.lineno,
                )
                end = node.end_lineno or node.lineno
                return start, end
    raise LookupError(f"no function definition at {file_path}:{site_line}")


def _run_matrix_json(instrument: str) -> dict[str, Any]:
    """Invoke ``watchfire matrix --instrument <X> --format json``."""
    result = subprocess.run(
        [
            "uv",
            "run",
            "watchfire",
            "matrix",
            "--instrument",
            instrument,
            "--format",
            "json",
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        sys.stderr.write(
            f"watchfire matrix --instrument {instrument} exited "
            f"{result.returncode}\n{result.stderr}\n"
        )
        sys.exit(1)
    return json.loads(result.stdout)


def _render_site(site: dict[str, Any], warnings: list[str]) -> str:
    """Render one ``??? quote`` block containing a snippet directive.

    On AST-lookup failure, fall back to a fixed ±20-line window so the
    page still renders, and record a warning for the bottom of the page.
    """
    rel_path = site["file"]
    def_line = int(site["line"])
    func_name = site["function"]

    abs_path = REPO_ROOT / rel_path
    try:
        start, end = function_range(abs_path, def_line)
    except LookupError as exc:
        warnings.append(f"- `{rel_path}:{def_line}` ({func_name}): {exc}")
        start = max(1, def_line - 1)
        end = def_line + 20

    return (
        f'??? quote "`{func_name}` — {rel_path}:{def_line}"\n'
        f"    ```python\n"
        f'    --8<-- "{rel_path}:{start}:{end}"\n'
        f"    ```\n"
    )


def _render_entry(entry: dict[str, Any], warnings: list[str]) -> str:
    """Render one ``### <key> — <title>`` section with one collapsible per site."""
    title = entry.get("title") or ""
    heading_suffix = f" — {title}" if title else ""
    out = [f"### {entry['key']}{heading_suffix}\n"]
    for site in entry["sites"]:
        out.append(_render_site(site, warnings))
    return "\n".join(out) + "\n"


def _render_instrument_section(
    section_heading: str,
    matrix: dict[str, Any],
    warnings: list[str],
) -> str:
    """Render the ``## <heading>`` section with all article subsections beneath."""
    out = [f"## {section_heading}\n"]
    entries = matrix.get("entries", [])
    if not entries:
        out.append("_No annotated functions for this instrument._\n")
        return "\n".join(out)
    for entry in entries:
        out.append(_render_entry(entry, warnings))
    return "\n".join(out)


def main() -> int:
    warnings: list[str] = []
    sections: list[str] = []
    for instrument_key, section_heading in INSTRUMENTS:
        matrix = _run_matrix_json(instrument_key)
        sections.append(_render_instrument_section(section_heading, matrix, warnings))

    body = PREAMBLE.format(generated_on=date.today().isoformat()) + "\n".join(sections)
    if warnings:
        body += (
            "\n---\n\n"
            "## Generator warnings\n\n"
            "The following sites could not be resolved to a function definition "
            "via AST; the snippet falls back to a fixed window. Investigate and "
            "fix the underlying issue (renamed function, refactored file, etc.).\n\n"
            + "\n".join(warnings)
            + "\n"
        )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(body, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
