"""
Row-level exposure-class scope — a property-secured leg that is NOT class (i).

Pipeline position:
    build_reporting_row_scope_bundle() -> RawDataBundle -> PipelineOrchestrator
        -> AggregatedResultBundle -> COREPGenerator

Why this portfolio exists. A handful of C 07.00 / OF 07.00 rows are scoped by
Annex II to ONE exposure class, with the instruction written as a sentence of
its own. Row 0040 is the CRR case:

    0040  of which: Secured by mortgages on immovable property - Residential
          property.  Article 125 CRR
          Only reported in exposure class 'Secured by mortgages on immovable
          property'
    -- COREP Annex II, C 07.00 rows table (crr-annex-ii-reporting-instructins.pdf,
       0-indexed p.90), quoted verbatim

Rows are evaluated PER SHEET over that sheet's own population, so a bare
``property_type == "residential"`` predicate reports the row on EVERY sheet that
holds a residential-property-secured leg, and the scope sentence has to be
carried as a term of its own. The engine does carry it
(``reporting/corep/c07.py::_SHEET_KEY_COL``) — and on the eight registered
reporting portfolios that term is **unobservable**: stripping it changes no
published figure anywhere, because no registered fixture puts a
residential-property-secured leg on a sheet other than ``real_estate``. The
scope was correct by the published instruction and by rule ``v7477_m``, and
untested: unreachable rather than undetected. This portfolio is the reachability.

## The three legs, and what each one is for

    ref                  | class      | sheet      | property_type | role
    ---------------------|------------|------------|---------------|--------------
    RSC-LN-ANCHOR        | corporate  | corporate  | (none)        | the separator
    RSC-LN-CORP-IPRE     | corporate  | corporate  | residential   | OUT OF SCOPE
    RSC-LN-RRE           | retail_    | real_      | residential   | the SURVIVOR
                         |  mortgage  |  estate    |               |

``RSC-LN-CORP-IPRE`` is the leg the scope acts on: 2,000,000 drawn against a
5,000,000 residential block, reported on the ``corporate`` sheet. Scoped, row
0040 is null there; unscoped it publishes 2,000,000 and breaks ``v7477_m``
(``{r0040} = empty``, live WARNING, scoped to every C 07.00 z-code except the
Total and the real-estate one) together with its C 07.00.b sibling ``v7478_m``.

``RSC-LN-RRE`` is the leg that must SURVIVE (``.claude/LESSONS.md`` B5's two-leg
pattern): 400,000 at the Art. 125(1)(a) 35%, so row 0040 on the ``real_estate``
sheet reads 400,000 / 140,000. Without it a test could not tell "the scope
works" from "row 0040 was zeroed everywhere".

``RSC-LN-ANCHOR`` keeps the ``corporate`` sheet total (3,000,000) different from
the out-of-scope leg (2,000,000), so "row 0040 is null on the corporate sheet"
cannot be satisfied by the sheet being empty, and row 0310's 2,000,000 cannot be
mistaken for the sheet total.

## Why the IPRE leg keeps its corporate class — and the column that does it

The mechanism is NOT the loan. Measured by varying one input at a time: the
exposure's ``has_income_cover`` is sourced entirely from the COLLATERAL's
``is_income_producing`` (``engine/hierarchy/enrich.py`` line 604 feeds
``income_cover`` from that column, and ``coalesce_attribute_levels`` resolves it
across the collateral's direct / facility / counterparty levels), so a
``has_income_cover`` set on the loan row is overwritten whenever property-LTV
collateral exists. With ``is_income_producing=True`` the leg stays ``corporate``
under both regimes; with it False the RE splitter reclassifies the secured part
to ``residential_mortgage`` and the leg lands on ``real_estate`` — where row 0040
is IN scope and this portfolio proves nothing. Setting the flag on the loan and
not on the collateral produced the split in both regimes, i.e. the loan flag is
inert on this path. That is why the flag lives on the collateral row here and
why no ``has_income_cover`` appears on the loan.

``engine/re_split/flagging.py::_re_split_candidate_gates`` is where it binds:
income-producing property is excluded from the loan-split candidate set. And the
regulation is the reason that is right rather than a convenience — CRR
Art. 125(2)(b) conditions the 35% on

    "the risk of the borrower shall not materially depend upon the performance of
    the underlying property or project, but on the underlying capacity of the
    borrower to repay the debt from other sources, and as a consequence, the
    repayment of the facility shall not materially depend on any cash flow
    generated by the underlying property serving as collateral"

so a corporate landlord repaying out of rents fails it, Art. 125 is unavailable,
and Art. 124(1) leaves the exposure where it is: a 100% risk weight "except for
any part of the exposure which is assigned to another exposure class". The leg is
a plain class-(g) corporate exposure that happens to be secured on a dwelling —
the shape a real loan book produces, and one the estate already holds on the
commercial side (``crr/art199``'s ``A199_LN_RE``, which never reaches C 07.00
because that portfolio is IRB-only).

## What it is NOT

- Not a statement that the class assignment itself is right. Whether a
  property-secured exposure failing Art. 125(2) belongs in Art. 112(1)(i) or in
  (g) is a separate question; this portfolio only requires that SOME reachable
  leg carries residential property on a non-(i) sheet, which is true under
  either answer.
- Not registered in ``RUNS``. It lights no previously-dead template column (row
  0040 column 0010 is already live on ``crr/rich`` and ``crr/re-split``), so
  ``.claude/LESSONS.md`` B5's registration requirement does not bite, and
  registering it would move the supervisory register and the cell-coverage
  census for information ``test_c07_row_scope.py`` obtains by evaluating the
  published rule directly.
- Not a CCF / off-balance-sheet portfolio. Every leg is 100% drawn so nothing
  sits between the pledge and the row under test.

References:
- COREP Annex II, C 07.00 rows 0040 / 0290 / 0310
- PRA PS1/26 Annex II, OF 07.00 rows 0330 / 0331 / 0332 (the same scope sentence)
- CRR Art. 124(1): the 100% weight where Art. 125 / 126 are not met
- CRR Art. 125(1)(a) / 125(2)(b) / 125(2)(d): the 35% and its conditions
- EBA v7477_m / v7478_m: ``{r0040} = empty`` outside exposure class (i)
"""

from __future__ import annotations

from datetime import date

import polars as pl

from rwa_calc.contracts.bundles import RawDataBundle
from tests.fixtures.raw_bundle import make_raw_bundle

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_VALUE_DATE = date(2024, 12, 31)
_MATURITY = date(2031, 12, 31)  # > both reporting dates (CRR 2025, B31 2027)

CP_CORP = "RSC-CP-CORP"
CP_INDIVIDUAL = "RSC-CP-IND"

#: The unsecured separator, so the corporate sheet total is not the IPRE leg.
LN_ANCHOR = "RSC-LN-ANCHOR"
#: The out-of-scope leg: residential property, class (g) corporate.
LN_CORP_IPRE = "RSC-LN-CORP-IPRE"
#: The in-scope survivor: a natural-person residential mortgage, class (i).
LN_RRE = "RSC-LN-RRE"

DRAWN_ANCHOR: float = 1_000_000.0
DRAWN_CORP_IPRE: float = 2_000_000.0
DRAWN_RRE: float = 400_000.0

#: The corporate sheet's row 0010. Different from ``DRAWN_CORP_IPRE`` on purpose.
CORPORATE_SHEET_TOTAL: float = DRAWN_ANCHOR + DRAWN_CORP_IPRE

#: Property values. The IPRE block is deliberately far larger than the loan
#: (LTV 0.40) so the exposure is unambiguously "fully secured" in Art. 124(1)'s
#: sense and the only reason Art. 125 does not apply is Art. 125(2)(b).
VALUE_CORP_IPRE: float = 5_000_000.0
VALUE_RRE: float = 800_000.0
LTV_CORP_IPRE: float = DRAWN_CORP_IPRE / VALUE_CORP_IPRE  # 0.40
LTV_RRE: float = DRAWN_RRE / VALUE_RRE  # 0.50 — inside the Art. 125(2)(d) 80%

#: CQS 3 on the corporate obligor, so its own weight is a table lookup rather
#: than the unrated default. Both regimes then weight the anchor and the IPRE leg
#: identically, which is what makes the two 0010 figures add cleanly.
CQS_CORP: int = 3


# ---------------------------------------------------------------------------
# Main public entry point
# ---------------------------------------------------------------------------


def build_reporting_row_scope_bundle() -> RawDataBundle:
    """Assemble the row-scope portfolio as a sealed ``RawDataBundle``.

    Run it through ``PipelineOrchestrator().run_with_data`` under either regime
    with ``PermissionMode.STANDARDISED`` — every leg is SA, and row 0040 is an SA
    template row.
    """
    return make_raw_bundle(
        counterparties=_counterparties(),
        loans=_loans(),
        collateral=_collateral(),
        ratings=_ratings(),
    )


# ---------------------------------------------------------------------------
# Table builders (private)
# ---------------------------------------------------------------------------


def _counterparties() -> pl.DataFrame:
    """One large corporate and one natural person.

    The natural person is what puts the survivor leg in ``retail_mortgage`` and
    therefore on the merged Art. 112(1)(i) sheet; the corporate is what keeps the
    out-of-scope leg on letter (g).
    """
    return pl.DataFrame(
        [
            {
                "counterparty_reference": CP_CORP,
                "counterparty_name": CP_CORP,
                "entity_type": "corporate",
                "country_code": "GB",
                "annual_revenue": 250_000_000.0,
                "default_status": False,
            },
            {
                "counterparty_reference": CP_INDIVIDUAL,
                "counterparty_name": CP_INDIVIDUAL,
                "entity_type": "individual",
                "country_code": "GB",
                "default_status": False,
            },
        ]
    )


def _loans() -> pl.DataFrame:
    """Three drawn, on-balance-sheet senior term loans.

    Note what the IPRE row does NOT carry: no ``property_type``, no ``ltv``, no
    ``has_income_cover``. All three are supplied by its collateral row, which is
    the level that wins (see the module docstring) — and a ``property_type`` on
    the loan would classify the leg into the real-estate family directly, which
    is the opposite of what this portfolio needs.
    """
    return pl.DataFrame(
        [
            _loan(LN_ANCHOR, CP_CORP, DRAWN_ANCHOR),
            _loan(LN_CORP_IPRE, CP_CORP, DRAWN_CORP_IPRE),
            # The survivor keys its class off the loan's own property_type, as
            # every residential-mortgage fixture in the estate does.
            _loan(LN_RRE, CP_INDIVIDUAL, DRAWN_RRE, property_type="residential", ltv=LTV_RRE),
        ]
    )


def _collateral() -> pl.DataFrame:
    """Two residential-property pledges that differ ONLY in income production.

    That is the whole design: the same ``property_type`` on both, so the row
    predicate matches both legs, and one difference that decides which sheet each
    leg is reported on.
    """
    return pl.DataFrame(
        [
            {
                "collateral_reference": "RSC-COLL-IPRE",
                "collateral_type": "real_estate",
                "property_type": "residential",
                "currency": "GBP",
                "market_value": VALUE_CORP_IPRE,
                "nominal_value": VALUE_CORP_IPRE,
                "property_ltv": LTV_CORP_IPRE,
                # THE load-bearing flag. See the module docstring: this is the
                # column the exposure's has_income_cover is sourced from, and it
                # is what keeps the leg off the real-estate sheet.
                "is_income_producing": True,
                "beneficiary_type": "loan",
                "beneficiary_reference": LN_CORP_IPRE,
                "valuation_date": _VALUE_DATE,
                "valuation_type": "market",
            },
            {
                "collateral_reference": "RSC-COLL-RRE",
                "collateral_type": "real_estate",
                "property_type": "residential",
                "currency": "GBP",
                "market_value": VALUE_RRE,
                "nominal_value": VALUE_RRE,
                "property_ltv": LTV_RRE,
                "is_income_producing": False,
                "beneficiary_type": "loan",
                "beneficiary_reference": LN_RRE,
                "valuation_date": _VALUE_DATE,
                "valuation_type": "market",
            },
        ]
    )


def _ratings() -> pl.DataFrame:
    """An external CQS on the corporate obligor; no internal PD anywhere.

    No ``model_permissions`` is supplied either, so every leg is SA under any
    permission mode — the portfolio cannot silently route IRB and report nothing
    on C 07.00.
    """
    return pl.DataFrame(
        [
            {
                "rating_reference": "RSC-RTG-CORP",
                "counterparty_reference": CP_CORP,
                "rating_type": "external",
                "rating_agency": "TEST_AGENCY",
                "rating_value": "BBB",
                "cqs": CQS_CORP,
                "rating_date": _VALUE_DATE,
            }
        ]
    )


def _loan(
    reference: str,
    counterparty_reference: str,
    drawn: float,
    *,
    property_type: str | None = None,
    ltv: float | None = None,
) -> dict:
    """One plain drawn, on-balance-sheet, senior term loan."""
    row: dict = {
        "loan_reference": reference,
        "counterparty_reference": counterparty_reference,
        "product_type": "term_loan",
        "drawn_amount": drawn,
        "currency": "GBP",
        "value_date": _VALUE_DATE,
        "maturity_date": _MATURITY,
        "seniority": "senior",
        "is_defaulted": False,
    }
    if property_type is not None:
        row["property_type"] = property_type
    if ltv is not None:
        row["ltv"] = ltv
    return row
