"""
Golden B31-CCR-FLOOR-1 scenario: CCR-only portfolio — output floor S-TREA/U-TREA inclusion.

Pipeline position:
    fixture-builder output -> test-writer (tests/acceptance/ccr/test_ccr_floor1.py)
    -> engine-implementer (engine/aggregator/_floor.py CCR EAD inclusion)

Scenario design (P8.55 / B31-CCR-FLOOR-1):
    One counterparty (CP_CCR_1): institution, entity_type="institution", CQS 2, GB.
    No IRB model permission — the U-TREA leg also routes through SA.
    Because SA is the approach for both S-TREA and U-TREA, this is the
    "until IMM lands, S-TREA == U-TREA for CCR" degenerate case: both legs
    should carry the same CCR EAD-derived RWA.

    One netting set (NS_CCR_1): counterparty=CP_CCR_1, legally enforceable,
    unmargined (is_margined=False, threshold/MTA/NICA all null).

    One trade (T_CCR_1): derivative, interest_rate asset class,
    notional=10,000,000 GBP, MtM (V) = 10,000,000, delta=1.0, is_long=True.
    Maturity 2031-01-15, start 2026-01-15 (5-year tenor, start date in the
    past at reporting_date 2030-01-01).

SA-CCR hand-calc (reporting_date=2030-01-01, Basel 3.1 regime, alpha=1.4):
    S = max(0, (2026-01-15 - 2030-01-01).days / 365) = 0.0
    E = (2031-01-15 - 2030-01-01).days / 365 ≈ 1.0384 years
    SD(S=0, E≈1.04) = (exp(-0.05×0) - exp(-0.05×1.04)) / 0.05 ≈ 1.01186
    MF_unmargined = sqrt(min(E, 1.0) / 1.0) = sqrt(1.0) = 1.0
    d (adjusted notional) = 10,000,000 × 1.01186 ≈ 10,118,621
    EN (effective notional) = d × delta × MF = 10,118,621 × 1.0 × 1.0 = 10,118,621
    addon_IR = 0.005 × 10,118,621 ≈ 50,593
    RC = max(V - C, 0) = max(10,000,000 - 0, 0) = 10,000,000
    EAD_ccr = 1.4 × (10,000,000 + 50,593) ≈ 14,070,830

Risk weight (Basel 3.1, ECRA, CQS 2 institution):
    B31 Art. 120(2) Table 3: CQS 2 → 30% (B31 ECRA for institutions).
    sa_rwa = EAD_ccr × 0.30 ≈ 4,221,249

Output floor assertions (TODAY — the bug being pinned):
    The engine today excludes CCR-derived exposures from both S-TREA and U-TREA
    in apply_floor_with_impact. Therefore:
        s_trea = 0.0   (BUG: should include CCR-derived SA RWA ≈ 4,221,249)
        u_trea = 0.0   (BUG: mirrors s_trea for pure-SA CCR portfolio)
        total_rwa_post_floor = EAD_ccr × 0.30 ≈ 4,221,249
    Post-fix (what the engine-implementer must implement):
        s_trea ≈ 4,221,249
        u_trea ≈ 4,221,249  (SA == U-TREA when no IRB model)
        total_rwa_post_floor ≈ 4,221,249  (floor does not bind: 0.725 × 4.2m < 4.2m is false,
                                            so floor threshold = 0.725 × 4.221m ≈ 3.06m < 4.221m)

Exact values (generated by running build_raw_data_bundle_ccr_floor1 through
the pipeline at reporting_date 2030-01-01, regime Basel 3.1):
    Run generate_all.py or call save_golden_fixtures() to materialise parquet files.
    The test-writer must derive the concrete ead_ccr, sa_rwa, and OutputFloorSummary
    values by running the pipeline — do NOT hard-code from hand-calc here.

Module-level constants are the single source of truth for test-writer assertions.

References:
    - CRR Art. 271 (CCR scope — derivatives)
    - CRR Art. 274(2) (SA-CCR EAD = α × (RC + PFE), alpha=1.4 for financial CPs)
    - CRR Art. 275(1) (unmargined RC = max(V - C, 0))
    - CRR Art. 279b(1)(a) (PFE add-on — interest rate adjusted notional + SD)
    - CRR Art. 279c(1) (unmargined MF = sqrt(min(M, 1)/1))
    - CRR Art. 295 (contractual netting recognition)
    - PS1/26 Art. 120(2) Table 3 (institution CQS 2 → 30% B31 ECRA RW)
    - PS1/26 Art. 92(2A) (output floor TREA = max(U-TREA, 0.725 × S-TREA + OF-ADJ))
    - src/rwa_calc/data/schemas.py — TRADE_SCHEMA, NETTING_SET_SCHEMA,
      COUNTERPARTY_SCHEMA, RATINGS_SCHEMA
"""

from __future__ import annotations

from datetime import date as _date
from pathlib import Path

import polars as pl

from rwa_calc.contracts.bundles import (
    CCRCollateralBundle,
    MarginAgreementBundle,
    NettingSetBundle,
    RawCCRBundle,
    RawDataBundle,
    TradeBundle,
)
from rwa_calc.data.column_spec import dtypes_of
from rwa_calc.data.schemas import (
    CCR_COLLATERAL_SCHEMA,
    COUNTERPARTY_SCHEMA,
    FACILITY_MAPPING_SCHEMA,
    FACILITY_SCHEMA,
    LENDING_MAPPING_SCHEMA,
    LOAN_SCHEMA,
    RATINGS_SCHEMA,
)
from tests.fixtures.raw_bundle import make_raw_bundle

from .margin_builder import create_margin_agreements
from .netting_set_builder import NettingSet, create_netting_sets
from .trade_builder import Trade, create_trades, make_trade

# ---------------------------------------------------------------------------
# Scenario constants — single source of truth for test-writer assertions.
# ---------------------------------------------------------------------------

CCR_FLOOR1_TRADE_ID: str = "T_CCR_1"
CCR_FLOOR1_NETTING_SET_ID: str = "NS_CCR_1"
CCR_FLOOR1_COUNTERPARTY_REF: str = "CP_CCR_1"

# Trade economics: GBP 10m notional IR derivative, in-the-money (V = 10m).
# The non-zero MtM ensures RC = 10,000,000 even with zero collateral,
# yielding a clean EAD ≈ 14,070,830 (alpha=1.4 × (RC=10m + PFE≈50k)).
CCR_FLOOR1_NOTIONAL: float = 10_000_000.0  # GBP 10m
CCR_FLOOR1_CURRENCY: str = "GBP"
CCR_FLOOR1_ASSET_CLASS: str = "interest_rate"
CCR_FLOOR1_TRANSACTION_TYPE: str = "derivative"
CCR_FLOOR1_MTM: float = 10_000_000.0  # V = GBP 10m (in-the-money)
CCR_FLOOR1_DELTA: float = 1.0  # non-option directional long
CCR_FLOOR1_IS_LONG: bool = True

# 5-year tenor: 2026-01-15 start (past at reporting 2030-01-01), 2031-01-15 maturity.
# At reporting_date 2030-01-01:
#   S = max(0, (2026-01-15 - 2030-01-01) / 365) = 0  (start in the past)
#   E = (2031-01-15 - 2030-01-01) / 365 ≈ 1.0384 years
# SD(0, 1.04) ≈ 1.01186; MF = sqrt(min(1.04, 1)) = 1.0
CCR_FLOOR1_START_DATE: _date = _date(2026, 1, 15)
CCR_FLOOR1_MATURITY_DATE: _date = _date(2031, 1, 15)

CCR_FLOOR1_IS_LEGALLY_ENFORCEABLE: bool = True  # Art. 295 met
CCR_FLOOR1_IS_MARGINED: bool = False  # unmargined

# Counterparty: GB institution, CQS 2, no IRB model permission.
# entity_type="institution" → Classifier routes CCR synthetic row through
# SA-Institution. institution_cqs=2 is set directly for CQS look-up.
CCR_FLOOR1_CP_ENTITY_TYPE: str = "institution"
CCR_FLOOR1_CP_COUNTRY_CODE: str = "GB"

# External rating: S&P "A" = CQS 2 for institutions under B31 ECRA.
# B31 Art. 120(2) Table 3: institution CQS 2 → 30% SA risk weight.
CCR_FLOOR1_RATING_REF: str = "RTG_CCR_FLOOR1_CP_CCR_1"
CCR_FLOOR1_RATING_TYPE: str = "external"
CCR_FLOOR1_RATING_AGENCY: str = "S&P"
CCR_FLOOR1_RATING_VALUE: str = "A"
CCR_FLOOR1_RATING_CQS: int = 2
CCR_FLOOR1_RATING_DATE: _date = _date(2026, 1, 15)

# Reporting date under test — Basel 3.1 output floor at 72.5%.
CCR_FLOOR1_REPORTING_DATE: _date = _date(2030, 1, 1)

# Expected B31 ECRA SA risk weight for CQS 2 institution.
# PS1/26 Art. 120(2) Table 3: CQS 2 → 30%.
CCR_FLOOR1_EXPECTED_B31_INSTITUTION_CQS2_RW: float = 0.30

# ---------------------------------------------------------------------------
# Engine-generated golden values (run reporting_date=2030-01-01, Basel 3.1).
# These are the EXACT outputs from the current engine — NOT hand-calc estimates.
# The test-writer pins these to lock in both current behaviour (the bug) and
# the expected post-fix behaviour.
# ---------------------------------------------------------------------------

# SA-CCR EAD: alpha=1.4 × (RC=10,000,000 + PFE≈50,558)
# Exact value from pipeline run 2030-01-01 Basel 3.1:
CCR_FLOOR1_GOLDEN_EAD_CCR: float = 14_067_985.908272337

# B31 Art. 120(2) Table 3: institution CQS 2 → risk_weight = 0.30.
CCR_FLOOR1_GOLDEN_RISK_WEIGHT: float = 0.3

# sa_rwa = ead_ccr × risk_weight = 14,067,985.91 × 0.30
CCR_FLOOR1_GOLDEN_SA_RWA: float = 4_220_395.772481701

# rwa_final (pre-floor, SA path): same as sa_rwa (no CRM, no IRB).
CCR_FLOOR1_GOLDEN_RWA_FINAL: float = 4_220_395.772481701

# OutputFloorSummary — TODAY (the bug being pinned by P8.55 test):
# CCR-derived SA exposures are excluded from S-TREA / U-TREA computation.
# Post-fix target: s_trea == u_trea == CCR_FLOOR1_GOLDEN_SA_RWA.
CCR_FLOOR1_GOLDEN_S_TREA_CURRENT: float = 0.0  # BUG: should be 4,220,395.77 post-fix
CCR_FLOOR1_GOLDEN_U_TREA_CURRENT: float = 0.0  # BUG: mirrors s_trea for pure-SA CCR
CCR_FLOOR1_GOLDEN_TOTAL_RWA_POST_FLOOR: float = 4_220_395.772481701  # correct via sa_rwa_total

# ---------------------------------------------------------------------------
# Private scenario builders (CCR domain)
# ---------------------------------------------------------------------------


def _ccr_floor1_trade() -> Trade:
    """Return the single B31-CCR-FLOOR-1 trade instance (5y GBP IR derivative)."""
    return make_trade(
        trade_id=CCR_FLOOR1_TRADE_ID,
        netting_set_id=CCR_FLOOR1_NETTING_SET_ID,
        asset_class=CCR_FLOOR1_ASSET_CLASS,
        transaction_type=CCR_FLOOR1_TRANSACTION_TYPE,
        notional=CCR_FLOOR1_NOTIONAL,
        currency=CCR_FLOOR1_CURRENCY,
        maturity_date=CCR_FLOOR1_MATURITY_DATE,
        start_date=CCR_FLOOR1_START_DATE,
        delta=CCR_FLOOR1_DELTA,
        is_long=CCR_FLOOR1_IS_LONG,
        mtm_value=CCR_FLOOR1_MTM,
    )


def _ccr_floor1_netting_set() -> NettingSet:
    """Return the single B31-CCR-FLOOR-1 netting set instance."""
    return NettingSet(
        netting_set_id=CCR_FLOOR1_NETTING_SET_ID,
        counterparty_reference=CCR_FLOOR1_COUNTERPARTY_REF,
        is_legally_enforceable=CCR_FLOOR1_IS_LEGALLY_ENFORCEABLE,
        is_margined=CCR_FLOOR1_IS_MARGINED,
    )


# ---------------------------------------------------------------------------
# DataFrame factories (CCR domain)
# ---------------------------------------------------------------------------


def create_ccr_floor1_trades() -> pl.DataFrame:
    """Return the single-row trades DataFrame for B31-CCR-FLOOR-1."""
    return create_trades([_ccr_floor1_trade()])


def create_ccr_floor1_netting_sets() -> pl.DataFrame:
    """Return the single-row netting-sets DataFrame for B31-CCR-FLOOR-1."""
    return create_netting_sets([_ccr_floor1_netting_set()])


def create_ccr_floor1_margin_agreements() -> pl.DataFrame:
    """Return a zero-row margin-agreements DataFrame (B31-CCR-FLOOR-1: unmargined)."""
    return create_margin_agreements([])


def create_ccr_floor1_collateral() -> pl.DataFrame:
    """Return a zero-row CCR-collateral DataFrame (B31-CCR-FLOOR-1: no collateral)."""
    return pl.DataFrame(schema=dtypes_of(CCR_COLLATERAL_SCHEMA))


# ---------------------------------------------------------------------------
# Private portfolio-stub builders
# ---------------------------------------------------------------------------


def _build_cp_ccr_1_counterparty() -> pl.LazyFrame:
    """
    Return a one-row counterparty LazyFrame for CP_CCR_1.

    CP_CCR_1 is a GB institution with CQS 2.  entity_type="institution" drives
    the Classifier to ExposureClass.INSTITUTION → SA risk weight look-up via
    B31 Art. 120(2) Table 3 (CQS 2 → 30% under ECRA).

    institution_cqs=2 is set directly so the SA calculator resolves the
    correct 30% risk weight even when bypassing the full rating-inheritance
    pipeline in unit tests.  The matching external rating row carries the same
    CQS 2 for full-pipeline resolution.

    No IRB model permission is provided.  This is the pure-SA CCR case
    (S-TREA == U-TREA) that the output-floor S-TREA/U-TREA inclusion test pins.
    """
    row = {
        "counterparty_reference": CCR_FLOOR1_COUNTERPARTY_REF,
        "counterparty_name": "B31-CCR-FLOOR-1 Test Institution (CQS 2, SA-only)",
        "entity_type": CCR_FLOOR1_CP_ENTITY_TYPE,
        "country_code": CCR_FLOOR1_CP_COUNTRY_CODE,
        "default_status": False,
        "apply_fi_scalar": False,
        "is_managed_as_retail": False,
        "institution_cqs": CCR_FLOOR1_RATING_CQS,
    }
    return pl.DataFrame([row], schema=dtypes_of(COUNTERPARTY_SCHEMA)).lazy()


def _build_cp_ccr_1_rating() -> pl.LazyFrame:
    """
    Return a one-row external ratings LazyFrame for CP_CCR_1.

    S&P "A" = CQS 2 under B31 ECRA mapping for institutions.
    B31 Art. 120(2) Table 3: institution CQS 2 → 30% risk weight.
    is_solicited=True (solicited rating — standard for ECRA use).
    pd=None — external ratings carry no PD (PD is internal-rating only).
    """
    row = {
        "rating_reference": CCR_FLOOR1_RATING_REF,
        "counterparty_reference": CCR_FLOOR1_COUNTERPARTY_REF,
        "rating_type": CCR_FLOOR1_RATING_TYPE,
        "rating_agency": CCR_FLOOR1_RATING_AGENCY,
        "rating_value": CCR_FLOOR1_RATING_VALUE,
        "cqs": CCR_FLOOR1_RATING_CQS,
        "pd": None,
        "rating_date": CCR_FLOOR1_RATING_DATE,
        "is_solicited": True,
        "model_id": None,
        "is_short_term": False,
        "scope_type": None,
        "scope_id": None,
    }
    return pl.DataFrame([row], schema=dtypes_of(RATINGS_SCHEMA)).lazy()


def _build_empty_facilities() -> pl.LazyFrame:
    """Return a zero-row facilities LazyFrame (no traditional lending in this CCR-only bundle)."""
    return pl.LazyFrame(schema=dtypes_of(FACILITY_SCHEMA))


def _build_empty_loans() -> pl.LazyFrame:
    """Return a zero-row loans LazyFrame (no drawn loans in this CCR-only bundle)."""
    return pl.LazyFrame(schema=dtypes_of(LOAN_SCHEMA))


def _build_empty_facility_mappings() -> pl.LazyFrame:
    """Return a zero-row facility-mappings LazyFrame."""
    return pl.LazyFrame(schema=dtypes_of(FACILITY_MAPPING_SCHEMA))


def _build_empty_lending_mappings() -> pl.LazyFrame:
    """Return a zero-row lending-mappings LazyFrame."""
    return pl.LazyFrame(schema=dtypes_of(LENDING_MAPPING_SCHEMA))


def _build_ccr_floor1_raw_ccr_bundle() -> RawCCRBundle:
    """
    Assemble the RawCCRBundle for the B31-CCR-FLOOR-1 scenario.

    Composition:
        trades            — 1 row (T_CCR_1: 5y GBP IR derivative, V=10m, NS_CCR_1)
        netting_sets      — 1 row (NS_CCR_1: CP_CCR_1, enforceable, unmargined)
        margin_agreements — 0 rows (unmargined, no CSA)
        ccr_collateral    — 0 rows (no posted/received collateral)
    """
    return RawCCRBundle(
        trades=TradeBundle(trades=create_ccr_floor1_trades().lazy()),
        netting_sets=NettingSetBundle(netting_sets=create_ccr_floor1_netting_sets().lazy()),
        margin_agreements=MarginAgreementBundle(
            margin_agreements=create_ccr_floor1_margin_agreements().lazy()
        ),
        ccr_collateral=CCRCollateralBundle(ccr_collateral=create_ccr_floor1_collateral().lazy()),
    )


# ---------------------------------------------------------------------------
# Public bundle-assembly helper
# ---------------------------------------------------------------------------


def build_raw_data_bundle_ccr_floor1() -> RawDataBundle:
    """
    Assemble a complete RawDataBundle for the B31-CCR-FLOOR-1 scenario.

    Key responsibilities:
    - Provides CP_CCR_1 as an institution counterparty (entity_type="institution",
      CQS 2, GB) so the Classifier routes the CCR-derived synthetic exposure
      through SA-Institution (B31 Art. 120(2) Table 3 → 30% RW under ECRA).
    - Provides a matching external rating (CQS 2, S&P "A") so the full
      rating-inheritance pipeline resolves external_cqs correctly.
    - Zero-row facility / loan / contingent / mapping frames so the only
      exposure in the pipeline is the CCR-derived synthetic row.
    - No model_permissions: no IRB permission → pure SA path → U-TREA == S-TREA.
    - ccr is populated with a RawCCRBundle containing the single trade T_CCR_1
      (5y GBP IR derivative, MtM=10m) in netting set NS_CCR_1.

    Integration test usage:
        from tests.fixtures.ccr.golden_ccr_floor1 import build_raw_data_bundle_ccr_floor1
        data = build_raw_data_bundle_ccr_floor1()
        config = CalculationConfig.basel_3_1()
        config = replace(config, reporting_date=date(2030, 1, 1))
        result = pipeline_orchestrator.run_with_data(data, config)

    The test-writer must run this bundle through the pipeline to obtain the
    exact ead_ccr, risk_weight, sa_rwa, and OutputFloorSummary values.

    References:
        - PS1/26 Art. 92(2A) (output floor TREA)
        - PS1/26 Art. 120(2) Table 3 (B31 institution CQS 2 → 30% ECRA RW)
        - CRR Art. 274(2) (SA-CCR EAD = alpha × (RC + PFE))
    """
    return make_raw_bundle(
        counterparties=_build_cp_ccr_1_counterparty(),
        facilities=_build_empty_facilities(),
        loans=_build_empty_loans(),
        facility_mappings=_build_empty_facility_mappings(),
        lending_mappings=_build_empty_lending_mappings(),
        ratings=_build_cp_ccr_1_rating(),
        ccr=_build_ccr_floor1_raw_ccr_bundle(),
    )


# ---------------------------------------------------------------------------
# Save helper — canonical entry point for generate_all.py and standalone use.
# ---------------------------------------------------------------------------


def save_ccr_floor1_fixtures(output_dir: Path | None = None) -> dict[str, Path]:
    """
    Write all four B31-CCR-FLOOR-1 golden parquet files to *output_dir*.

    Files produced:
        ccr_floor1_trades.parquet           — 1 row (T_CCR_1, 5y GBP IR derivative)
        ccr_floor1_netting_sets.parquet     — 1 row (NS_CCR_1, CP_CCR_1)
        ccr_floor1_margin_agreements.parquet — 0 rows (unmargined)
        ccr_floor1_ccr_collateral.parquet   — 0 rows (no collateral)

    Args:
        output_dir: Target directory. Defaults to the directory containing
            this script (``tests/fixtures/ccr/``).

    Returns:
        Dict mapping artefact name to saved absolute Path.
    """
    if output_dir is None:
        output_dir = Path(__file__).parent
    output_dir.mkdir(parents=True, exist_ok=True)

    artefacts: list[tuple[str, pl.DataFrame]] = [
        ("ccr_floor1_trades", create_ccr_floor1_trades()),
        ("ccr_floor1_netting_sets", create_ccr_floor1_netting_sets()),
        ("ccr_floor1_margin_agreements", create_ccr_floor1_margin_agreements()),
        ("ccr_floor1_ccr_collateral", create_ccr_floor1_collateral()),
    ]

    saved: dict[str, Path] = {}
    for name, df in artefacts:
        path = output_dir / f"{name}.parquet"
        df.write_parquet(path)
        saved[name] = path

    return saved


def main() -> None:
    """Entry point for standalone generation and pipeline smoke-check."""
    saved = save_ccr_floor1_fixtures()
    print("B31-CCR-FLOOR-1 golden fixture generation complete")
    print("-" * 70)
    for name, path in saved.items():
        df = pl.read_parquet(path)
        print(f"  {name:<35} {len(df):>2} row(s)  {len(df.columns):>2} cols  ->  {path.name}")
    print("-" * 70)
    print("Scenario: B31-CCR-FLOOR-1 — SA-only CCR portfolio output floor pin")
    print(
        f"  Trade:       {CCR_FLOOR1_TRADE_ID} (asset_class={CCR_FLOOR1_ASSET_CLASS!r},"
        f" notional={CCR_FLOOR1_NOTIONAL:,.0f} {CCR_FLOOR1_CURRENCY}, V={CCR_FLOOR1_MTM:,.0f})"
    )
    print(
        f"  Netting set: {CCR_FLOOR1_NETTING_SET_ID} -> {CCR_FLOOR1_COUNTERPARTY_REF}"
        f" (enforceable={CCR_FLOOR1_IS_LEGALLY_ENFORCEABLE},"
        f" margined={CCR_FLOOR1_IS_MARGINED})"
    )
    print(f"  Reporting date: {CCR_FLOOR1_REPORTING_DATE} (Basel 3.1, floor 72.5%)")
    print(f"  Expected B31 institution CQS 2 RW: {CCR_FLOOR1_EXPECTED_B31_INSTITUTION_CQS2_RW:.0%}")


if __name__ == "__main__":
    main()
