"""
Golden CCR-IRB-1 scenario: single 5-year GBP vanilla IR swap, unmargined,
IRB-permissioned corporate counterparty (F-IRB, CRR Art. 153(1)).

Pipeline position:
    fixture-builder output -> test-writer (tests/acceptance/ccr/test_ccr_irb1.py)
    -> engine-implementer (engine/ccr/pipeline_adapter.py model_id enrichment)

Scenario design (P8.31 / CCR-IRB-1):
    One trade (T_IRB_001): 5-year GBP vanilla IR swap, notional GBP 100m,
    MtM = 0.0 (at-par), delta = 1.0 (non-option directional long).
    One netting set (NS_IRB_001): counterparty CP_IRB_001, legally enforceable
    (Art. 295 condition met), unmargined.
    Zero margin agreements: no CSA in place.
    Zero CCR collateral: no posted or received collateral.

Counterparty design:
    CP_IRB_001: entity_type="corporate", country_code="GB", non-SME.
    A matching internal rating row carries pd=0.0150 and model_id="MOD_CORP_FIRB"
    so that the hierarchy pipeline promotes them to internal_pd=0.0150 and
    internal_model_id="MOD_CORP_FIRB" on the counterparty_lookup frame.

    The classifier resolves approach_applied=foundation_irb for the CCR-derived
    synthetic row once engine/ccr/pipeline_adapter.py is fixed to carry model_id
    through to the synthetic exposure row (the load-bearing gap documented in the
    P8.31 proposal).  Until that engine fix lands, approach_applied falls back to
    standardised; the fixture still supplies all the data.

Model permission:
    MOD_CORP_FIRB → exposure_class="corporate", approach="foundation_irb", GB.
    This row must be added to the model_permissions fixture (see
    tests/fixtures/model_permissions/model_permissions.py) or provided inline
    as model_permissions on a ResolvedHierarchyBundle.  This file adds it to
    the shared model_permissions.parquet via
    ``create_ccr_irb1_model_permission()``.

SA-CCR EAD hand-calc (for cross-check; GOLDEN MUST BE GENERATED by pipeline):
    SF_IR = 0.005; supervisory_delta = 1.0; MF_unmargined = sqrt(min(5,1)/1) = 1.0
    Supervisory duration SD(S=0, E=5) = (exp(-0.05×0)−exp(-0.05×5)) / 0.05 ≈ 4.323
    Adjusted notional = 100_000_000 × 4.323 ≈ 432_332_358
    Effective notional (EN) = 432_332_358 × 1.0 × 1.0 (delta × MF) = 432_332_358
    Add-on_IR = 0.005 × 432_332_358 ≈ 2_161_662
    RC = max(0 − 0, 0) = 0
    EAD_ccr = 1.4 × (0 + 2_161_662) ≈ 3_026_327
    Note: exact value generated by pipeline run; 5-year swap < CCR-A1 10-year swap
    (CCR-A1 ead_ccr ≈ 5_480_018 with supervisory duration for 10-year tenor).

IRB K hand-calc (CRR Art. 153(1), for cross-check; GOLDEN MUST BE GENERATED):
    PD = max(0.0150, 0.0003) = 0.0150; LGD = 0.45 (Art. 161(1)(a) F-IRB senior
    unsecured); M = clip(5.0, 1, 5) = 5.0
    R ≈ 0.12 × (1 − exp(−50×0.0150)) / (1 − exp(−50))
        + 0.24 × [1 − (1 − exp(−50×0.0150)) / (1 − exp(−50))]
      ≈ 0.12 × 0.527 + 0.24 × 0.473 ≈ 0.176568
    b = (0.11852 − 0.05478 × ln(0.0150))^2 ≈ 0.121508
    MA = (1 + (M − 2.5) × b) / (1 − 1.5 × b) ≈ 1.594607
    K = (LGD × N((N⁻¹(PD) + sqrt(R) × N⁻¹(0.999)) / sqrt(1 − R)) − LGD × PD) × MA
      ≈ 0.069095 (scaling factor 1.06 already included in K formula — see CRR)
    risk_weight = K × 12.5 ≈ 145.99% (includes 1.06 scaling)
    RWA = risk_weight × EAD_ccr (generated)

Expected output assertions for test-writer (exposure_reference = "ccr__NS_IRB_001"):
    risk_type = CCR_DERIVATIVE
    source_netting_set_id = NS_IRB_001
    ccr_method = sa_ccr
    ead_ccr = generated (< 5_480_018 — 5-year < 10-year)
    ead_final == ead_ccr  (no CRM; load-bearing identity)
    exposure_class = corporate
    approach_applied = foundation_irb  (LOAD-BEARING — requires P8.31 engine fix)
    pd / pd_floored ≈ 0.0150
    lgd / lgd_floored = 0.45
    irb_maturity_m = 5.0
    k ≈ 0.069095 (generated — polars-normal-stats may differ in last ulp)
    risk_weight ≈ 1.459913  (generated)
    rwa_final = risk_weight × ead_ccr  (generated)

Golden file note:
    ead_ccr, k, risk_weight, and rwa_final are NOT hand-typed constants in this
    fixture.  The test-writer must generate the golden JSON by running the full
    CRR pipeline over the bundle returned by ``build_raw_data_bundle_ccr_irb1()``
    and writing the result to tests/expected_outputs/ccr/CCR-IRB-1.json using
    the same generation pattern as CCR-A1.  This file supplies only the
    structural data; golden generation belongs to the test layer.

References:
    - CRR Art. 153(1) (IRB K formula for corporate)
    - CRR Art. 161(1)(a) (F-IRB senior unsecured LGD = 45%)
    - CRR Art. 162(2)(b) (non-IMM maturity: weighted-average remaining, 1y–5y clip)
    - CRR Art. 163 (PD floor 0.03%)
    - CRR Art. 274(2) (SA-CCR EAD = α·(RC + PFE))
    - CRR Art. 279b (PFE add-on — interest rate asset class)
    - CRR Art. 295 (contractual netting recognition)
    - src/rwa_calc/data/schemas.py — TRADE_SCHEMA, NETTING_SET_SCHEMA,
      COUNTERPARTY_SCHEMA, RATINGS_SCHEMA, MODEL_PERMISSIONS_SCHEMA
"""

from __future__ import annotations

from datetime import date as _date
from pathlib import Path

import polars as pl

from rwa_calc.contracts.bundles import (
    CCRCollateralBundle,
    MarginAgreementBundle,
    NettingSetBundle,
    RawCCRBundle,
    RawDataBundle,
    TradeBundle,
)
from rwa_calc.data.column_spec import dtypes_of
from rwa_calc.data.schemas import (
    CCR_COLLATERAL_SCHEMA,
    COUNTERPARTY_SCHEMA,
    FACILITY_MAPPING_SCHEMA,
    FACILITY_SCHEMA,
    LENDING_MAPPING_SCHEMA,
    LOAN_SCHEMA,
    MODEL_PERMISSIONS_SCHEMA,
    RATINGS_SCHEMA,
)

from .margin_builder import create_margin_agreements
from .netting_set_builder import NettingSet, create_netting_sets
from .trade_builder import Trade, create_trades, make_trade

# ---------------------------------------------------------------------------
# Scenario constants — single source of truth for test-writer assertions.
# ---------------------------------------------------------------------------

CCR_IRB1_TRADE_ID: str = "T_IRB_001"
CCR_IRB1_NETTING_SET_ID: str = "NS_IRB_001"
CCR_IRB1_COUNTERPARTY_REF: str = "CP_IRB_001"

CCR_IRB1_NOTIONAL: float = 100_000_000.0  # GBP 100m
CCR_IRB1_CURRENCY: str = "GBP"
CCR_IRB1_ASSET_CLASS: str = "interest_rate"
CCR_IRB1_TRANSACTION_TYPE: str = "derivative"
CCR_IRB1_MTM: float = 0.0  # at-par vanilla swap
CCR_IRB1_DELTA: float = 1.0  # non-option directional long
CCR_IRB1_IS_LONG: bool = True

# 5-year tenor: 2026-01-15 start, 2031-01-15 maturity.
CCR_IRB1_START_DATE: _date = _date(2026, 1, 15)
CCR_IRB1_MATURITY_DATE: _date = _date(2031, 1, 15)

CCR_IRB1_IS_LEGALLY_ENFORCEABLE: bool = True  # Art. 295 condition met
CCR_IRB1_IS_MARGINED: bool = False  # unmargined

# ---------------------------------------------------------------------------
# Counterparty constants.
# ---------------------------------------------------------------------------

# CP_IRB_001: corporate, GB, non-SME (annual_revenue omitted → null → conservative large).
# entity_type="corporate" → Classifier routes to ExposureClass.CORPORATE.
CCR_IRB1_CP_ENTITY_TYPE: str = "corporate"
CCR_IRB1_CP_COUNTRY_CODE: str = "GB"

# ---------------------------------------------------------------------------
# Internal rating / model constants.
# ---------------------------------------------------------------------------

# Internal rating row: pd=0.0150, model_id="MOD_CORP_FIRB".
# CRR Art. 163: PD floor 0.03% — 1.50% is well above floor.
# CRR Art. 161(1)(a): F-IRB senior unsecured corporate LGD = 45%.
CCR_IRB1_RATING_REF: str = "RTG_CCR_IRB1_CP_IRB_001"
CCR_IRB1_RATING_TYPE: str = "internal"
CCR_IRB1_INTERNAL_PD: float = 0.0150  # 1.50% — above CRR Art. 163 floor of 0.03%
CCR_IRB1_RATING_DATE: _date = _date(2026, 1, 15)

# Model permission: MOD_CORP_FIRB → corporate → foundation_irb.
# This model_id must appear in the model_permissions parquet / bundle.
CCR_IRB1_MODEL_ID: str = "MOD_CORP_FIRB"
CCR_IRB1_MODEL_EXPOSURE_CLASS: str = "corporate"
CCR_IRB1_MODEL_APPROACH: str = "foundation_irb"
CCR_IRB1_MODEL_COUNTRY_CODES: str = "GB"

# ---------------------------------------------------------------------------
# Expected IRB parameters (for test-writer cross-check assertions).
# ---------------------------------------------------------------------------

# CRR Art. 163: PD floor 0.03% → floored PD = max(0.0150, 0.0003) = 0.0150
CCR_IRB1_PD_FLOORED: float = 0.0150
# CRR Art. 161(1)(a): F-IRB senior unsecured LGD = 45%.
CCR_IRB1_LGD: float = 0.45
# CRR Art. 162(2)(b): M = clip(5.0, 1, 5) = 5.0 for this single-trade netting set.
CCR_IRB1_MATURITY_M: float = 5.0


# ---------------------------------------------------------------------------
# Private scenario builders (CCR domain)
# ---------------------------------------------------------------------------


def _ccr_irb1_trade() -> Trade:
    """Return the single CCR-IRB-1 trade instance (5-year GBP IR swap)."""
    return make_trade(
        trade_id=CCR_IRB1_TRADE_ID,
        netting_set_id=CCR_IRB1_NETTING_SET_ID,
        asset_class=CCR_IRB1_ASSET_CLASS,
        transaction_type=CCR_IRB1_TRANSACTION_TYPE,
        notional=CCR_IRB1_NOTIONAL,
        currency=CCR_IRB1_CURRENCY,
        maturity_date=CCR_IRB1_MATURITY_DATE,
        start_date=CCR_IRB1_START_DATE,
        delta=CCR_IRB1_DELTA,
        is_long=CCR_IRB1_IS_LONG,
        mtm_value=CCR_IRB1_MTM,
    )


def _ccr_irb1_netting_set() -> NettingSet:
    """Return the single CCR-IRB-1 netting set instance."""
    return NettingSet(
        netting_set_id=CCR_IRB1_NETTING_SET_ID,
        counterparty_reference=CCR_IRB1_COUNTERPARTY_REF,
        is_legally_enforceable=CCR_IRB1_IS_LEGALLY_ENFORCEABLE,
        is_margined=CCR_IRB1_IS_MARGINED,
    )


# ---------------------------------------------------------------------------
# DataFrame factories (CCR domain)
# ---------------------------------------------------------------------------


def create_ccr_irb1_trades() -> pl.DataFrame:
    """Return the single-row trades DataFrame for CCR-IRB-1."""
    return create_trades([_ccr_irb1_trade()])


def create_ccr_irb1_netting_sets() -> pl.DataFrame:
    """Return the single-row netting-sets DataFrame for CCR-IRB-1."""
    return create_netting_sets([_ccr_irb1_netting_set()])


def create_ccr_irb1_margin_agreements() -> pl.DataFrame:
    """Return a zero-row margin-agreements DataFrame (CCR-IRB-1: no CSA)."""
    return create_margin_agreements([])


def create_ccr_irb1_collateral() -> pl.DataFrame:
    """Return a zero-row CCR-collateral DataFrame (CCR-IRB-1: no collateral)."""
    return pl.DataFrame(schema=dtypes_of(CCR_COLLATERAL_SCHEMA))


# ---------------------------------------------------------------------------
# Private portfolio-stub builders (counterparty + rating + model permission)
# ---------------------------------------------------------------------------


def _build_cp_irb_001_counterparty() -> pl.LazyFrame:
    """
    Return a one-row counterparty LazyFrame for CP_IRB_001.

    CP_IRB_001 is a GB corporate.  entity_type="corporate" drives the Classifier
    to ExposureClass.CORPORATE.  No annual_revenue set → null → conservative large
    corporate (CLS008 baseline).  Once P8.31 engine fix lands, the classifier reads
    model_id from the internal rating (via counterparty_lookup) and routes to
    ExposureClass.CORPORATE / approach=foundation_irb.

    No institution_cqs needed (this is a corporate, not an institution).
    No scra_grade, no external rating — IRB path uses internal_pd only.
    """
    row = {
        "counterparty_reference": CCR_IRB1_COUNTERPARTY_REF,
        "counterparty_name": "CCR-IRB-1 Test Corporate (F-IRB)",
        "entity_type": CCR_IRB1_CP_ENTITY_TYPE,
        "country_code": CCR_IRB1_CP_COUNTRY_CODE,
        "default_status": False,
        "apply_fi_scalar": False,
        "is_managed_as_retail": False,
    }
    return pl.DataFrame([row], schema=dtypes_of(COUNTERPARTY_SCHEMA)).lazy()


def _build_cp_irb_001_rating() -> pl.LazyFrame:
    """
    Return a one-row internal ratings LazyFrame for CP_IRB_001.

    rating_type="internal" with pd=0.0150 and model_id="MOD_CORP_FIRB".
    The hierarchy pipeline promotes these to:
        internal_pd=0.0150 (via alias pl.col("pd").alias("internal_pd"))
        internal_model_id="MOD_CORP_FIRB" (via alias pl.col("model_id").alias("internal_model_id"))
    on the counterparty_lookup frame.

    cqs=None — internal ratings carry no external CQS (PD path only).
    is_solicited=False — internal (own-model) rating is not solicited.

    References:
        - CRR Art. 163: PD floor 0.03% → pd=0.0150 is above floor.
        - CRR Art. 161(1)(a): F-IRB senior unsecured LGD resolved by engine.
    """
    row = {
        "rating_reference": CCR_IRB1_RATING_REF,
        "counterparty_reference": CCR_IRB1_COUNTERPARTY_REF,
        "rating_type": CCR_IRB1_RATING_TYPE,
        "rating_agency": None,
        "rating_value": None,
        "cqs": None,
        "pd": CCR_IRB1_INTERNAL_PD,
        "rating_date": CCR_IRB1_RATING_DATE,
        "is_solicited": False,
        "model_id": CCR_IRB1_MODEL_ID,
        "is_short_term": False,
        "scope_type": None,
        "scope_id": None,
    }
    return pl.DataFrame([row], schema=dtypes_of(RATINGS_SCHEMA)).lazy()


def create_ccr_irb1_model_permission() -> pl.DataFrame:
    """
    Return a one-row model-permission DataFrame for MOD_CORP_FIRB.

    MOD_CORP_FIRB grants foundation_irb for corporate exposures in GB.
    This row must be merged with the shared model_permissions fixture, or
    supplied to the pipeline via RawDataBundle.model_permissions when the
    standard model_permissions.parquet does not yet contain this entry.

    The test-writer should combine this with the shared model_permissions
    or use a standalone bundle.  The row is intentionally kept separate from
    the main model_permissions fixture to avoid polluting the shared fixture
    with a CCR-specific scenario model_id.

    See: tests/fixtures/model_permissions/model_permissions.py
         tests/acceptance/ccr/test_ccr_irb1.py
    """
    row = {
        "model_id": CCR_IRB1_MODEL_ID,
        "exposure_class": CCR_IRB1_MODEL_EXPOSURE_CLASS,
        "approach": CCR_IRB1_MODEL_APPROACH,
        "country_codes": CCR_IRB1_MODEL_COUNTRY_CODES,
        "excluded_book_codes": None,
    }
    return pl.DataFrame([row], schema=dtypes_of(MODEL_PERMISSIONS_SCHEMA))


def _build_empty_facilities() -> pl.LazyFrame:
    """Return a zero-row facilities LazyFrame (no traditional lending in CCR-IRB-1 bundle)."""
    return pl.LazyFrame(schema=dtypes_of(FACILITY_SCHEMA))


def _build_empty_loans() -> pl.LazyFrame:
    """Return a zero-row loans LazyFrame (no drawn loans in CCR-IRB-1 bundle)."""
    return pl.LazyFrame(schema=dtypes_of(LOAN_SCHEMA))


def _build_empty_facility_mappings() -> pl.LazyFrame:
    """Return a zero-row facility-mappings LazyFrame (no facility hierarchy in CCR-IRB-1 bundle)."""
    return pl.LazyFrame(schema=dtypes_of(FACILITY_MAPPING_SCHEMA))


def _build_empty_lending_mappings() -> pl.LazyFrame:
    """Return a zero-row lending-mappings LazyFrame (no retail lending groups in CCR-IRB-1 bundle)."""
    return pl.LazyFrame(schema=dtypes_of(LENDING_MAPPING_SCHEMA))


def _build_ccr_irb1_raw_ccr_bundle() -> RawCCRBundle:
    """
    Assemble the RawCCRBundle from the four CCR-IRB-1 domain frames.

    Composition:
        trades            — 1 row  (T_IRB_001, 5y GBP IR swap, NS_IRB_001)
        netting_sets      — 1 row  (NS_IRB_001, CP_IRB_001, enforceable, unmargined)
        margin_agreements — 0 rows (CCR-IRB-1: unmargined, no CSA)
        ccr_collateral    — 0 rows (CCR-IRB-1: no posted/received collateral)
    """
    return RawCCRBundle(
        trades=TradeBundle(trades=create_ccr_irb1_trades().lazy()),
        netting_sets=NettingSetBundle(netting_sets=create_ccr_irb1_netting_sets().lazy()),
        margin_agreements=MarginAgreementBundle(
            margin_agreements=create_ccr_irb1_margin_agreements().lazy()
        ),
        ccr_collateral=CCRCollateralBundle(ccr_collateral=create_ccr_irb1_collateral().lazy()),
    )


# ---------------------------------------------------------------------------
# Public bundle-assembly helper (P8.31)
# ---------------------------------------------------------------------------


def build_raw_data_bundle_ccr_irb1() -> RawDataBundle:
    """
    Assemble a complete RawDataBundle for the CCR-IRB-1 scenario (P8.31).

    Key responsibilities:
    - Provides CP_IRB_001 as a corporate counterparty (entity_type="corporate", GB)
      so the Classifier can route the CCR-derived synthetic exposure to
      ExposureClass.CORPORATE (SA fallback today; F-IRB once P8.31 engine fix lands).
    - Provides an internal rating (pd=0.0150, model_id="MOD_CORP_FIRB") so the
      hierarchy pipeline attaches internal_pd=0.0150 and internal_model_id="MOD_CORP_FIRB"
      to the counterparty_lookup frame.
    - model_permissions is None here: the test must supply the MOD_CORP_FIRB
      model permission via a full ModelPermissionsBundle or via a combined
      model_permissions.parquet that includes the CCR-IRB-1 row.  Use
      ``create_ccr_irb1_model_permission()`` to build the permission row.
    - Zero-row facility / loan / contingent / mapping frames so the only
      exposure in the pipeline is the CCR-derived synthetic row.
    - ``ccr`` is populated with a RawCCRBundle containing trade T_IRB_001
      (5y GBP IR swap) in netting set NS_IRB_001 (CP_IRB_001, enforceable,
      unmargined), with empty margin and collateral frames.

    Golden values:
        ead_ccr, k, risk_weight, rwa_final are NOT embedded here.
        The test-writer must run the pipeline over this bundle, capture the
        output, and write tests/expected_outputs/ccr/CCR-IRB-1.json using
        the same generation pattern as CCR-A1.

    Integration test usage::

        from tests.fixtures.ccr.golden_ccr_irb1 import (
            build_raw_data_bundle_ccr_irb1,
            create_ccr_irb1_model_permission,
        )
        data = build_raw_data_bundle_ccr_irb1()
        result = pipeline_orchestrator.run_with_data(data, config)

    References:
        - CRR Art. 153(1) (corporate IRB K formula)
        - CRR Art. 161(1)(a) (F-IRB senior unsecured LGD = 45%)
        - CRR Art. 274(2) (SA-CCR EAD = alpha × (RC + PFE))
    """
    return RawDataBundle(
        counterparties=_build_cp_irb_001_counterparty(),
        facilities=_build_empty_facilities(),
        loans=_build_empty_loans(),
        facility_mappings=_build_empty_facility_mappings(),
        lending_mappings=_build_empty_lending_mappings(),
        ratings=_build_cp_irb_001_rating(),
        ccr=_build_ccr_irb1_raw_ccr_bundle(),
    )


# ---------------------------------------------------------------------------
# Save helper — canonical entry point for generate_all.py and standalone use.
# ---------------------------------------------------------------------------


def save_ccr_irb1_fixtures(output_dir: Path | None = None) -> dict[str, Path]:
    """
    Write all four CCR-IRB-1 parquet files to *output_dir*.

    Files produced:
        ccr_irb1_trades.parquet           — 1 row  (T_IRB_001, 5y GBP IR swap)
        ccr_irb1_netting_sets.parquet     — 1 row  (NS_IRB_001, CP_IRB_001, enforceable)
        ccr_irb1_margin_agreements.parquet — 0 rows (unmargined, no CSA)
        ccr_irb1_ccr_collateral.parquet   — 0 rows (no collateral)

    The model permission row is NOT written here — it is supplied separately
    via ``create_ccr_irb1_model_permission()`` for the test-writer to merge
    with the shared model_permissions fixture or bundle standalone.

    Args:
        output_dir: Target directory.  Defaults to the directory containing
            this script (``tests/fixtures/ccr/``).

    Returns:
        Dict mapping artefact name to saved absolute ``Path``.
    """
    if output_dir is None:
        output_dir = Path(__file__).parent
    output_dir.mkdir(parents=True, exist_ok=True)

    artefacts: list[tuple[str, pl.DataFrame]] = [
        ("ccr_irb1_trades", create_ccr_irb1_trades()),
        ("ccr_irb1_netting_sets", create_ccr_irb1_netting_sets()),
        ("ccr_irb1_margin_agreements", create_ccr_irb1_margin_agreements()),
        ("ccr_irb1_ccr_collateral", create_ccr_irb1_collateral()),
    ]

    saved: dict[str, Path] = {}
    for name, df in artefacts:
        path = output_dir / f"{name}.parquet"
        df.write_parquet(path)
        saved[name] = path

    return saved


def save_ccr_irb1_smoke_check() -> list[tuple[str, int]]:
    """
    Smoke-check the CCR-IRB-1 bundle and return a generation report.

    Validates structural invariants expected by the test-writer and
    generates the four CCR parquet files.  The model permission row
    is validated in-memory only (not written to disk here).

    Invariants checked:
        1.  bundle.ccr is not None.
        2.  Trades frame has exactly 1 row: T_IRB_001, asset_class="interest_rate".
        3.  Trade notional = 100_000_000, currency = GBP, delta = 1.0.
        4.  Trade start_date = 2026-01-15, maturity_date = 2031-01-15 (5-year tenor).
        5.  Netting-set frame has exactly 1 row: NS_IRB_001.
        6.  NS_IRB_001: counterparty_reference=CP_IRB_001, is_legally_enforceable=True,
            is_margined=False.
        7.  Margin-agreements frame has 0 rows.
        8.  CCR-collateral frame has 0 rows.
        9.  Counterparty frame has exactly 1 row: CP_IRB_001, entity_type="corporate".
        10. Rating frame has exactly 1 row: internal, pd=0.0150, model_id="MOD_CORP_FIRB".
        11. Model permission row: model_id="MOD_CORP_FIRB", approach="foundation_irb".

    Returns:
        List of (filename, row_count) tuples for generate_all.py reporting.
    """
    bundle = build_raw_data_bundle_ccr_irb1()

    # --- Invariant 1: CCR bundle present ---
    if bundle.ccr is None:
        raise AssertionError("CCR-IRB-1: bundle.ccr must not be None")

    trades_df = bundle.ccr.trades.trades.collect()
    ns_df = bundle.ccr.netting_sets.netting_sets.collect()
    margin_df = bundle.ccr.margin_agreements.margin_agreements.collect()
    collateral_df = bundle.ccr.ccr_collateral.ccr_collateral.collect()
    cp_df = bundle.counterparties.collect()
    rating_df = bundle.ratings.collect() if bundle.ratings is not None else pl.DataFrame()

    # --- Invariant 2: 1 trade row ---
    if trades_df.height != 1:
        raise AssertionError(f"CCR-IRB-1: expected 1 trade row, got {trades_df.height}")
    if trades_df["trade_id"][0] != CCR_IRB1_TRADE_ID:
        raise AssertionError(
            f"CCR-IRB-1: trade_id must be {CCR_IRB1_TRADE_ID!r} (got {trades_df['trade_id'][0]!r})"
        )
    if trades_df["asset_class"][0] != "interest_rate":
        raise AssertionError(
            f"CCR-IRB-1: asset_class must be 'interest_rate' (got {trades_df['asset_class'][0]!r})"
        )

    # --- Invariant 3: notional / currency / delta ---
    if trades_df["notional"][0] != CCR_IRB1_NOTIONAL:
        raise AssertionError(
            f"CCR-IRB-1: notional must be {CCR_IRB1_NOTIONAL} (got {trades_df['notional'][0]})"
        )
    if trades_df["currency"][0] != CCR_IRB1_CURRENCY:
        raise AssertionError(
            f"CCR-IRB-1: currency must be {CCR_IRB1_CURRENCY!r} (got {trades_df['currency'][0]!r})"
        )
    if trades_df["delta"][0] != CCR_IRB1_DELTA:
        raise AssertionError(
            f"CCR-IRB-1: delta must be {CCR_IRB1_DELTA} (got {trades_df['delta'][0]})"
        )

    # --- Invariant 4: dates ---
    import datetime  # noqa: PLC0415

    if trades_df["start_date"][0] != CCR_IRB1_START_DATE:
        raise AssertionError(
            f"CCR-IRB-1: start_date must be {CCR_IRB1_START_DATE} "
            f"(got {trades_df['start_date'][0]})"
        )
    if trades_df["maturity_date"][0] != CCR_IRB1_MATURITY_DATE:
        raise AssertionError(
            f"CCR-IRB-1: maturity_date must be {CCR_IRB1_MATURITY_DATE} "
            f"(got {trades_df['maturity_date'][0]})"
        )
    # Confirm 5-year tenor (shorter than CCR-A1 10-year).
    tenor_days = (datetime.date(2031, 1, 15) - datetime.date(2026, 1, 15)).days
    if not (1820 <= tenor_days <= 1827):  # ~5 years
        raise AssertionError(f"CCR-IRB-1: expected ~5-year tenor, got {tenor_days} days")

    # --- Invariant 5: 1 netting-set row ---
    if ns_df.height != 1:
        raise AssertionError(f"CCR-IRB-1: expected 1 netting-set row, got {ns_df.height}")
    if ns_df["netting_set_id"][0] != CCR_IRB1_NETTING_SET_ID:
        raise AssertionError(
            f"CCR-IRB-1: netting_set_id must be {CCR_IRB1_NETTING_SET_ID!r} "
            f"(got {ns_df['netting_set_id'][0]!r})"
        )

    # --- Invariant 6: legally enforceable, unmargined, correct counterparty ---
    if ns_df["counterparty_reference"][0] != CCR_IRB1_COUNTERPARTY_REF:
        raise AssertionError(
            f"CCR-IRB-1: NS counterparty_reference must be {CCR_IRB1_COUNTERPARTY_REF!r}"
        )
    if ns_df["is_legally_enforceable"][0] is not True:
        raise AssertionError("CCR-IRB-1: NS_IRB_001 is_legally_enforceable must be True")
    if ns_df["is_margined"][0] is not False:
        raise AssertionError("CCR-IRB-1: NS_IRB_001 is_margined must be False")

    # --- Invariant 7: zero margin rows ---
    if margin_df.height != 0:
        raise AssertionError(
            f"CCR-IRB-1: margin_agreements must be empty (got {margin_df.height} rows)"
        )

    # --- Invariant 8: zero collateral rows ---
    if collateral_df.height != 0:
        raise AssertionError(
            f"CCR-IRB-1: ccr_collateral must be empty (got {collateral_df.height} rows)"
        )

    # --- Invariant 9: 1 counterparty row, entity_type="corporate" ---
    if cp_df.height != 1:
        raise AssertionError(f"CCR-IRB-1: expected 1 counterparty row, got {cp_df.height}")
    if cp_df["counterparty_reference"][0] != CCR_IRB1_COUNTERPARTY_REF:
        raise AssertionError(
            f"CCR-IRB-1: counterparty_reference must be {CCR_IRB1_COUNTERPARTY_REF!r}"
        )
    if cp_df["entity_type"][0] != CCR_IRB1_CP_ENTITY_TYPE:
        raise AssertionError(
            f"CCR-IRB-1: entity_type must be {CCR_IRB1_CP_ENTITY_TYPE!r} "
            f"(got {cp_df['entity_type'][0]!r})"
        )

    # --- Invariant 10: 1 internal rating row, pd=0.0150, model_id="MOD_CORP_FIRB" ---
    if rating_df.height != 1:
        raise AssertionError(f"CCR-IRB-1: expected 1 rating row, got {rating_df.height}")
    if rating_df["rating_type"][0] != "internal":
        raise AssertionError(
            f"CCR-IRB-1: rating_type must be 'internal' (got {rating_df['rating_type'][0]!r})"
        )
    if rating_df["counterparty_reference"][0] != CCR_IRB1_COUNTERPARTY_REF:
        raise AssertionError("CCR-IRB-1: rating counterparty_reference mismatch")
    pd_val = rating_df["pd"][0]
    if pd_val is None or abs(pd_val - CCR_IRB1_INTERNAL_PD) > 1e-10:
        raise AssertionError(f"CCR-IRB-1: rating pd must be {CCR_IRB1_INTERNAL_PD} (got {pd_val})")
    if rating_df["model_id"][0] != CCR_IRB1_MODEL_ID:
        raise AssertionError(
            f"CCR-IRB-1: rating model_id must be {CCR_IRB1_MODEL_ID!r} "
            f"(got {rating_df['model_id'][0]!r})"
        )

    # --- Invariant 11: model permission row structure ---
    perm_df = create_ccr_irb1_model_permission()
    if perm_df.height != 1:
        raise AssertionError(f"CCR-IRB-1: model permission must have 1 row (got {perm_df.height})")
    if perm_df["model_id"][0] != CCR_IRB1_MODEL_ID:
        raise AssertionError(f"CCR-IRB-1: permission model_id must be {CCR_IRB1_MODEL_ID!r}")
    if perm_df["approach"][0] != CCR_IRB1_MODEL_APPROACH:
        raise AssertionError(
            f"CCR-IRB-1: permission approach must be {CCR_IRB1_MODEL_APPROACH!r} "
            f"(got {perm_df['approach'][0]!r})"
        )
    if perm_df["exposure_class"][0] != CCR_IRB1_MODEL_EXPOSURE_CLASS:
        raise AssertionError(
            f"CCR-IRB-1: permission exposure_class must be {CCR_IRB1_MODEL_EXPOSURE_CLASS!r}"
        )

    # Write parquet files and return report.
    saved = save_ccr_irb1_fixtures()
    return [(f"{name}.parquet", pl.read_parquet(path).height) for name, path in saved.items()]


def main() -> None:
    """Entry point for standalone generation."""
    from pathlib import Path as _Path  # noqa: PLC0415

    output_dir = _Path(__file__).parent
    saved = save_ccr_irb1_fixtures(output_dir)
    print("CCR-IRB-1 fixture generation complete")
    print("-" * 70)
    for name, path in saved.items():
        df = pl.read_parquet(path)
        print(f"  {name:<35} {len(df):>2} row(s)  {len(df.columns):>2} cols  ->  {path.name}")
    perm_df = create_ccr_irb1_model_permission()
    print(f"  {'model_permission (in-memory)':<35} {len(perm_df):>2} row(s)  (not written to disk)")
    print("-" * 70)
    print("Scenario: CCR-IRB-1 — 5y GBP IR swap, CP_IRB_001 (corporate, F-IRB), unmargined")
    print(
        f"  Trade:        {CCR_IRB1_TRADE_ID} (notional={CCR_IRB1_NOTIONAL:,.0f} {CCR_IRB1_CURRENCY},"
        f" tenor={CCR_IRB1_START_DATE}..{CCR_IRB1_MATURITY_DATE})"
    )
    print(
        f"  Netting set:  {CCR_IRB1_NETTING_SET_ID} -> {CCR_IRB1_COUNTERPARTY_REF}"
        f" (enforceable={CCR_IRB1_IS_LEGALLY_ENFORCEABLE}, margined={CCR_IRB1_IS_MARGINED})"
    )
    print(
        f"  Counterparty: {CCR_IRB1_COUNTERPARTY_REF} (entity_type={CCR_IRB1_CP_ENTITY_TYPE!r},"
        f" country={CCR_IRB1_CP_COUNTRY_CODE})"
    )
    print(f"  Rating:       internal, pd={CCR_IRB1_INTERNAL_PD}, model_id={CCR_IRB1_MODEL_ID!r}")
    print(
        f"  Permission:   {CCR_IRB1_MODEL_ID} -> {CCR_IRB1_MODEL_APPROACH} for"
        f" {CCR_IRB1_MODEL_EXPOSURE_CLASS} (country={CCR_IRB1_MODEL_COUNTRY_CODES})"
    )
    print()
    print("Golden note: ead_ccr / k / risk_weight / rwa_final are generated by the pipeline.")
    print("  Test-writer must run the pipeline and save CCR-IRB-1.json to")
    print("  tests/expected_outputs/ccr/CCR-IRB-1.json.")


if __name__ == "__main__":
    main()
